from pathlib import Path

ROOT = Path(__file__).parent
NAV = [('index.html','نقشه راه'),('competitors.html','رقبا'),('strategy.html','راهبرد'),('build-paths.html','مسیر ساخت'),('design.html','طراحی'),('templates.html','تمپلیت‌ها'),('woodmart-templates.html','وودمارت'),('security.html','امنیت'),('seo-roadmap.html','سئو'),('client-brief.html','اطلاعات کارفرما')]
STEPS = [
    ('discovery','شناخت و تصمیم','دیدن رقبا و پیدا کردن فرصت‌ها','اول سایت‌های مشابه را ببینیم؛ بعد عمق اطلاعات کالا، طراحی، سئو و مسیر استعلام آن‌ها را مقایسه کنیم.','فهرست رقبا و فرصت‌هایی که سایت ما باید پوشش دهد.','competitors.html#screenshots','دیدن رقبا و تصاویر', [('competitors.html#competitors','نقشه رقابت'),('competitors.html#start-here','خلاصه بررسی')]),
    ('strategy','شناخت و تصمیم','تعیین راهبرد و ساختار سایت','مشخص کنیم مشتری چگونه مدل کابل را پیدا می‌کند، چه مدرکی لازم دارد و کدام اقلام خرید آنلاین یا استعلامی‌اند.','اولویت صفحات، اطلاعات هر مدل و روش فروش.','strategy.html#priorities','تعیین اولویت‌های سایت', [('strategy.html','گزارش راهبرد'),('design.html#journey','مسیر خریدار'),('client-brief.html#brief-catalog','داده‌های لازم')]),
    ('seo','شناخت و تصمیم','چیدن برنامه سئو از شروع پروژه','نوع سبد و روش فروش را انتخاب کنیم و نقشه کلمه، صفحه و محتوا را پیش از ساخت مشخص کنیم. تجربه دیپلم‌سرا هم در گزارش آمده است.','صفحات هدف، خوشه‌های محتوا و برنامه شش‌ماهه.','seo-roadmap.html#paths','انتخاب مسیر سئو', [('seo-roadmap.html#case-study','نمونه دیپلم‌سرا'),('seo-roadmap.html#keyword-playbook','کلمه و صفحه'),('seo-roadmap.html#roadmap','برنامه شش‌ماهه')]),
    ('design','طراحی و اجرا','انتخاب شکل سایت و تمپلیت وودمارت','طرح‌های خانه، فهرست کالا، محصول، درباره، تماس و حساب را ببینیم و یک هویت منسجم برای اجرای المنتور انتخاب کنیم.','طرح منتخب و اجزای قابل اجرای آن در وودمارت.','woodmart-templates.html#gallery','دیدن طرح‌های وودمارت', [('design.html','منطق طراحی'),('templates.html','گالری تمپلیت‌ها'),('woodmart-templates.html#customer-pages','صفحات مشتری')]),
    ('build','طراحی و اجرا','مشخص کردن مسیر ساخت و مدیریت فروش','برای انتخاب فعلیِ وردپرس، اجرای وودمارت، المنتور و ووکامرس را به کارهای مشخص تبدیل کنیم؛ توسعه اختصاصی برای نیازهای اضافه بررسی شود.','دامنه اجرای نسخه اول، ابزارها و مسئول مدیریت کالا/قیمت.','build-paths.html#routes','دیدن مراحل ساخت', [('woodmart-templates.html#implementation','اجرای المنتور'),('woodmart-templates.html#pricing','مدیریت قیمت'),('build-paths.html#ai-editorial','محتوا با n8n و AI')]),
    ('security','طراحی و اجرا','طراحی امنیت، ورود و پیش‌فاکتور مشتری','دسترسی کارکنان، کد ورود، سند خصوصی، نسخه قیمت و برنامه بازیابی را پیش از فعال‌کردن حساب و فروش تعیین کنیم.','قواعد دسترسی، گردش سند و معیار پذیرش قابلیت‌ها.','security.html#security-plan','انتخاب مسیر امنیت', [('security.html#login','ورود و بازیابی'),('security.html#quotes','پیش‌فاکتور خصوصی'),('security.html#acceptance','معیار پذیرش')]),
    ('launch','راه‌اندازی و رشد','تحویل، راه‌اندازی و بهبود مستمر','پس از آماده‌شدن صفحات و داده واقعی، معیارهای تحویل بررسی شوند؛ سپس جست‌وجو، استعلام و فروش مبنای اصلاح ماهانه قرار بگیرند.','نسخه قابل تحویل، مسئول نگه‌داری و گزارش رشد.','seo-roadmap.html#measurement','برنامه سنجش و رشد', [('client-brief.html#brief-delivery','اطلاعات و تأیید کارفرما'),('security.html#delivery','مراحل تحویل'),('security.html#operations','نگه‌داری و بازیابی'),('seo-roadmap.html#deliverables','تحویل‌های سئو')]),
]

ICON_PATHS = {
    'discovery':'<rect x="3" y="4" width="7" height="7" rx="1.5"/><rect x="14" y="4" width="7" height="7" rx="1.5"/><path d="M5 17h14M12 11v6M5 17v3M19 17v3"/>',
    'strategy':'<path d="M4 5h8M4 10h12M4 15h7M4 20h16"/><circle cx="18" cy="5" r="3"/><path d="m16 16 2 2 4-5"/>',
    'seo':'<path d="M3 19V5M3 19h18M7 14l4-4 4 2 6-7M17 5h4v4"/>',
    'design':'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18M9 9v11M6 6.5h.01M9 6.5h.01"/>',
    'build':'<path d="m8 7-5 5 5 5m8-10 5 5-5 5m-3-13-2 20"/>',
    'security':'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z"/><path d="m8 12 3 3 5-6"/>',
    'launch':'<path d="M12 20V10m-5 5 5-5 5 5M5 20H3V5h18v15h-2"/><path d="M7 3v4m10-4v4"/>',
}

def icon(slug):
    return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+ICON_PATHS[slug]+'</svg>'

def step_html(i, step):
    slug, phase, title, text, output, url, cta, links = step
    number = str(i).translate(str.maketrans('0123456789','۰۱۲۳۴۵۶۷۸۹'))
    next_link = f'<a class="rm-next" href="#step-{STEPS[i][0]}">مرحله بعد: {STEPS[i][2]} ↓</a>' if i < len(STEPS) else '<a class="rm-next" href="#start-here">بازگشت به ابتدای مسیر ↑</a>'
    return f'''<li class="rm-step" id="step-{slug}"><span class="rm-number" aria-label="مرحله {number}">{number}</span><article class="rm-step-card"><div class="rm-step-copy"><div class="rm-card-heading"><span class="rm-step-icon">{icon(slug)}</span><div><span class="rm-phase">{phase}</span><h3>{title}</h3></div></div><p>{text}</p><div class="rm-output"><strong>خروجی این مرحله</strong><span>{output}</span></div></div><div class="rm-step-links"><a class="btn btn-primary" href="{url}">{cta} ←</a><div class="rm-connections">{''.join(f'<a href="{href}">{label} ↗</a>' for href,label in links)}</div>{next_link}</div></article></li>'''

nav = ''.join(f'<a href="{href}"'+(' aria-current="page"' if href=='index.html' else '')+f'>{label}</a>' for href,label in NAV)
short_labels = ['دیدن رقبا', 'راهبرد سایت', 'برنامه سئو', 'انتخاب طرح', 'مسیر ساخت', 'امنیت و فروش', 'راه‌اندازی و رشد']
phase_links = ''.join(f'<a href="#step-{s[0]}" data-roadmap-link="{s[0]}"><span>{i:02}</span><b>{short_labels[i-1]}</b><i aria-hidden="true">←</i></a>' for i,s in enumerate(STEPS,1))
DIRECTORY_META = [('discovery','شواهد بازار و اطلس تصاویر'),('strategy','اولویت‌ها و ساختار صفحات'),('build','ابزارها و مراحل پیاده‌سازی'),('design','منطق تجربه خریدار'),('design','سبک‌ها و نمونه صفحات'),('design','طرح‌های المنتور و فروشگاه'),('security','حساب، سند و دسترسی‌ها'),('seo','محتوا و برنامه رشد'),('strategy','داده‌های لازم برای شروع طراحی')]
directory = ''.join(f'<a href="{href}"><span class="rm-directory-icon">{icon(DIRECTORY_META[i][0])}</span><span class="rm-directory-copy"><strong>{label}</strong><small>{DIRECTORY_META[i][1]}</small></span><b aria-hidden="true">↗</b></a>' for i,(href,label) in enumerate(NAV[1:]))
html = f'''<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="نقشه راه ساخت سایت کابل: بررسی رقبا، راهبرد، سئو، طرح وودمارت، ساخت، امنیت و برنامه راه‌اندازی؛ پیوند مرحله‌به‌مرحله به همه گزارش‌ها."><title>نقشه راه سایت کابل | از بررسی رقبا تا اجرا و رشد</title><link rel="stylesheet" href="reports-site.css"><link rel="stylesheet" href="roadmap-home.css?v=roadmap-2"></head><body class="home-page roadmap-home">
<nav class="site-nav" aria-label="ناوبری اصلی"><div class="wrap"><a class="site-brand" href="index.html"><span class="brand-mark" aria-hidden="true">◎</span><span>پرونده بازار کابل</span></a><div class="nav-links">{nav}</div><div class="nav-actions"><button class="icon-btn" id="theme-toggle" type="button" aria-label="تغییر تم">☀</button></div></div><div class="reading-bar" id="reading-bar" aria-hidden="true"></div></nav>
<header class="hero hub-hero"><div class="wrap"><div><span class="eyebrow">پرونده طراحی و توسعه سایت</span><span class="rm-hero-label">نقشه راه پروژه / نسخه ارائه</span><h1>یک مسیر روشن؛<br>از شناخت بازار<br><em>تا ساخت و رشد سایت.</em></h1><p>این صفحه نقطه شروع پرونده است. هر مرحله یک تصمیم را روشن می‌کند و شما را به گزارش، طرح یا برنامه اجرایی مرتبط می‌رساند.</p><div class="hero-meta"><span>مسیر منتخب: وردپرس و وودمارت</span><span>کابل وارداتی و برندهای داخلی</span></div><div class="hero-actions"><a class="primary" href="#step-discovery">شروع از دیدن رقبا ←</a><a class="secondary" href="#reports">همه گزارش‌ها</a></div></div><div class="rm-hero-visual"><div class="rm-photo-frame"><img src="assets/cable-market-editorial.webp" alt="تصویر مفهومی کابل و قرقره صنعتی" fetchpriority="high"><div class="rm-photo-caption"><span>شناخت بازار، پایه تصمیم‌های طراحی</span><small>تصویر مفهومی</small></div></div><a class="rm-design-peek" href="woodmart-templates.html#gallery"><img src="assets/templates/woodmart-sliders/wave-home-desktop.png" alt="پیش‌نمایش طرح موج در گالری وودمارت"><span><b>از گزارش به طرح</b><small>دیدن نمونه‌های وودمارت ↗</small></span></a><div class="rm-hero-facts"><div><b>۷</b><span>مرحله مشخص</span></div><div><b>۱۰</b><span>سایت در بررسی رقبا</span></div><div><b>۷۸</b><span>تصویر تمپلیت</span></div></div></div></div></header>
<main class="wrap page-main"><section class="rm-overview" id="start-here"><div class="rm-overview-copy"><div class="kicker">مسیر در یک نگاه</div><h2>به ترتیب جلو بروید؛ به هر بخش هم مستقیم دسترسی دارید</h2><p>ابتدا بازار و صفحات هدف را بشناسیم، سپس طرح و اجرای سایت را مشخص کنیم و در پایان تحویل و رشد را پیگیری کنیم. امنیت و سئو از شروع طراحی در تصمیم‌ها حضور دارند.</p></div><div class="rm-phases"><a href="#step-discovery"><span>۰۱–۰۳</span><b>شناخت و تصمیم</b><small>رقبا · راهبرد · سئو</small></a><a href="#step-design"><span>۰۴–۰۶</span><b>طراحی و اجرا</b><small>تمپلیت · ساخت · امنیت</small></a><a href="#step-launch"><span>۰۷</span><b>راه‌اندازی و رشد</b><small>تحویل · سنجش · نگه‌داری</small></a></div></section>
<section class="rm-client-inputs" id="client-inputs"><div class="rm-inputs-icon" aria-hidden="true">＋</div><div><span class="kicker">ورودی مشترک همه مراحل</span><h2>کارفرما چه اطلاعاتی باید به ما بدهد؟</h2><p>تعداد محصولات و تنوع‌ها، دسته‌بندی، برندها، آدرس و تماس، قواعد قیمت و فروش، طرح دلخواه و امکانات نسخه اول؛ یک فرم مرتب برای جمع‌بندی نیازهای واقعی پروژه.</p></div><a class="btn btn-primary" href="client-brief.html">تکمیل اطلاعات کارفرما ←</a></section>
<section class="section" id="project-roadmap"><div class="section-head"><div><div class="kicker">نقشه راه به ترتیب</div><h2>در هر مرحله، چه تصمیمی می‌گیریم؟</h2><p>لینک اصلی هر مرحله شما را به نقطه شروع همان کار می‌برد؛ لینک‌های کناری، جزئیات مرتبط را باز می‌کنند.</p></div></div><div class="rm-layout"><aside class="rm-route-sidebar"><div class="rm-route-label"><span>مسیر پروژه</span><b>۰۱ — ۰۷</b></div><nav class="rm-shortcuts" aria-label="انتخاب مرحله">{phase_links}</nav><div class="rm-reading-state"><span class="rm-reading-dot" aria-hidden="true"></span><span id="rm-reading-label">شروع از بررسی رقبا</span></div><a class="rm-all-reports" href="#reports">فهرست تمام گزارش‌ها ↗</a></aside><ol class="rm-steps">{''.join(step_html(i,s) for i,s in enumerate(STEPS,1))}</ol></div><aside class="rm-note"><strong>وضعیت فعلی پرونده</strong><p>گزارش‌ها و نمونه‌های طراحی برای تصمیم‌گیری آماده‌اند. نام برندها، مدل‌ها و قواعد واقعی فروش هنوز باید تکمیل شوند؛ ورود، قیمت و پیش‌فاکتور نمونه‌ها نمایشی‌اند. اجرای وردپرس و اتصال سرویس‌ها در مرحله پیاده‌سازی انجام می‌شود.</p></aside></section>
<section class="section" id="reports"><div class="section-head"><div><div class="kicker">ارتباط با تمام صفحات پرونده</div><h2>دسترسی مستقیم به گزارش‌ها</h2><p>اگر بخش موردنظر را می‌دانید، از اینجا مستقیم باز کنید.</p></div></div><div class="rm-directory">{directory}</div></section>
<section class="section evidence-feature" id="visual-evidence"><div class="evidence-feature-copy"><div class="kicker">پیشنهاد شروع</div><h2>قبل از انتخاب طرح، رقبا را ببینید</h2><p>۱۰ سایت مرتبط در گزارش بررسی شده‌اند؛ ۱۸ تصویر دسکتاپ و گوشی از ۹ سایت، مشاهده شکل صفحات را آسان می‌کنند.</p><a class="btn btn-primary" href="competitors.html#screenshots">دیدن اطلس رقبا ←</a></div><div class="evidence-mosaic" aria-label="پیش‌نمایش تصاویر رقبا"><a href="competitors.html#shot-barghsan"><img src="competitor-screenshots/barghsan-desktop.jpg" alt="صفحه اصلی برق‌سان" loading="lazy"><span>برق‌سان</span></a><a href="competitors.html#shot-voltatadbir"><img src="competitor-screenshots/voltatadbir-desktop.jpg" alt="صفحه اصلی ولتا تدبیر" loading="lazy"><span>ولتا تدبیر</span></a><a href="competitors.html#shot-legrandco"><img src="competitor-screenshots/legrandco-desktop.jpg" alt="صفحه اصلی لگراندکو" loading="lazy"><span>لگراندکو</span></a></div></section>
</main><footer class="site-footer"><div class="wrap"><strong>نقشه راه سایت کابل · پرونده پروژه</strong><span>۱۱ مهر ۱۴۰۵ · از بررسی رقبا تا تحویل و رشد</span></div></footer><button class="toc-fab" id="toc-fab" type="button" aria-expanded="false" aria-controls="toc-panel">فهرست مرحله‌ها</button><nav class="toc-panel" id="toc-panel" aria-label="فهرست همین صفحه" hidden><strong>در این صفحه</strong></nav><script src="reports-site.js"></script><script src="roadmap-home.js?v=roadmap-2"></script></body></html>'''
(ROOT/'index.html').write_text(html,encoding='utf-8')
print('Roadmap homepage generated')
