"""Render the Persian service proposal from one structured, editable source."""
from pathlib import Path
from html import escape as esc
import copy
import json
import sys

ROOT=Path(__file__).resolve().parent
PRIVATE=ROOT
sys.path.insert(0,str(ROOT))
D=json.loads((PRIVATE/'service-plans.json').read_text(encoding='utf-8'))
P=D['plans']
FA=str.maketrans('0123456789','۰۱۲۳۴۵۶۷۸۹')
def fa(value):return str(value).translate(FA)
def ul(items):return '<ul>'+''.join('<li>'+esc(x)+'</li>' for x in items)+'</ul>'
def section(id,title,body,kicker='شرح خدمات'):
    return f'<section class="section" id="{id}"><div class="section-head"><div><div class="kicker">{kicker}</div><h2>{title}</h2></div></div>{body}</section>'

for p in P:
    if sum(row[1] for row in p['breakdown'])!=p['price']:raise ValueError('Price breakdown does not reconcile: '+p['id'])
    s=p['seo']
    if s['products']+s['categories']+s['brands']!=s['pages']:raise ValueError('SEO scope does not reconcile: '+p['id'])

def features(p):
    return copy.deepcopy(p['features'])

def acceptance_for(p):
    return copy.deepcopy(p['acceptance'])

def detail(p,i):
    s=p['seo']
    fields={**D['common'],**features(p)}
    blocks=''.join(f'<details class="sp-detail"'+(' open' if k in ['پیش‌فاکتور فوری بدون حساب','پایه‌گذاری سئو'] else '')+f'><summary>{esc(k)}</summary>{ul(v)}</details>' for k,v in fields.items())
    costs=''.join(f'<tr><td>{esc(label)}</td><td>{fa(value)}</td></tr>' for label,value in p['breakdown'])
    acceptance=acceptance_for(p)
    return f'''<article class="sp-plan-detail" id="plan-{p['id']}" data-plan="{p['id']}">
<div class="sp-detail-head"><div><span class="kicker">پلن {fa(i)} / {esc(p['name'])}</span><h2>{esc(p['subtitle'])}</h2><p>{esc(p['fit'])}</p></div><div class="sp-total"><b>{fa(p['price'])}</b><span>میلیون تومان · ساخت اولیه</span><small>{p['days']} روز کاری</small></div></div>
<div class="sp-design-note"><strong>دامنه دقیق طراحی</strong><p>{esc(p['design'])}</p></div>
<div class="sp-seo-scope"><div><span class="kicker">سئوی داخل همین مبلغ</span><h3>{fa(s['pages'])} صفحه منتخب + {fa(s['articles'])} مقاله آغاز</h3><p>{esc(s['description'])}</p></div><div class="sp-seo-counts"><span><b>{fa(s['products'])}</b>مدل</span><span><b>{fa(s['categories'])}</b>دسته</span><span><b>{fa(s['brands'])}</b>برند</span><span><b>{fa(s['clusters'])}</b>خوشه</span></div><small>{esc(s['followup'])}؛ پیگیری فنی اولیه داخل هزینه ساخت است، تولید و بهینه‌سازی ماهانه جداست.</small></div>
<div class="sp-detail-columns"><div>{blocks}<details class="sp-detail"><summary>خدمات خارج از این پلن</summary>{ul(p['excluded'])}<p>هزینه‌های مشترک خارج از قرارداد در <a href="#boundaries">مرز تعهدات</a> آمده‌اند.</p></details></div><aside><div class="sp-cost"><h3>این مبلغ چگونه تقسیم شده؟</h3><table><thead><tr><th>کار</th><th>میلیون</th></tr></thead><tbody>{costs}</tbody><tfoot><tr><th>جمع دقیق</th><th>{fa(p['price'])}</th></tr></tfoot></table><p>سهم هر بخش برای شفافیت پکیج است؛ قیمت خرید تکیِ همان ماژول محسوب نمی‌شود.</p></div><div class="sp-acceptance"><h3>چه چیزی مبنای تحویل است؟</h3>{ul(acceptance)}</div></aside></div>
<div class="sp-plan-actions"><a class="btn btn-secondary" href="service-plan-{p['id']}.txt" download>دانلود شرح کامل این پلن ↓</a><a class="btn btn-secondary" href="client-brief.html#brief-catalog">اطلاعات لازم از کارفرما</a><a class="btn btn-primary" href="#budget" data-budget-plan="{p['id']}">محاسبه بودجه این پلن ←</a></div></article>'''

nav='<div class="nav-links">'+(ROOT/'build-paths.html').read_text('utf-8').split('<div class="nav-links">',1)[1].split('</div>',1)[0]+'</div>'
nav=nav.replace(' aria-current="page"','')
if 'service-plans.html' not in nav:nav=nav.replace('<a href="design.html"','<a href="service-plans.html" aria-current="page">پلن‌ها و قیمت</a><a href="design.html"',1)
else:nav=nav.replace('<a href="service-plans.html"','<a href="service-plans.html" aria-current="page"',1)

cards=''.join(f'''<a class="sp-plan-card {'sp-recommended' if p['recommended'] else ''}" href="#plan-{p['id']}" data-plan-select="{p['id']}"><span class="sp-card-label">پلن {fa(i+1)}{' · پیشنهاد شروع' if p['recommended'] else ''}</span><h2>{esc(p['name'])}</h2><p>{esc(p['subtitle'])}</p><div class="sp-card-price"><b>{fa(p['price'])}</b><span>میلیون تومان</span></div><div class="sp-card-facts"><span>{p['days']} روز کاری</span><span>{fa(p['seo']['pages'])} صفحه سئو</span><span>{fa(p['seo']['articles'])} مقاله آغاز</span></div><strong>شرح کامل و معیار تحویل ←</strong></a>''' for i,p in enumerate(P))
rows=[('قیمت ساخت اولیه',[fa(p['price'])+' میلیون' for p in P]),('روش طراحی',['اختصاصی با المنتور/وودمارت']*4),('داده و کالا',['۳۰۰ SKU آماده · مبنای موقت']*4),('هدف فروش',['تماس + پیش‌فاکتور فوری']*4),('حساب و ثبت‌نام مشتری',['ندارد']*4),('مدیریت قیمت',['ووکامرس / CSV استاندارد']*4),('ارسال سند',['ایمیل فروش؛ نسخه مشتری اختیاری']*4),('بات بله',['گزینه اضافه']*4),('امنیت و بازیابی',['در همه پلن‌ها']*4),('پایه‌گذاری اختصاصی سئو',['شامل نیست','شامل','شامل','شامل']),('صفحات منتخب با اصلاح دستی',[fa(p['seo']['pages']) for p in P]),('راهنمای فنی اولیه',[fa(p['seo']['articles']) for p in P]),('سئوی مستمر',['قرارداد ماهانه جدا']*4),('n8n/AI محتوا',['شامل نیست','شامل نیست','شامل نیست','پژوهش/پیش‌نویس با تأیید متخصص'])]
matrix='<div class="sp-table"><table><thead><tr><th>خروجی قابل مقایسه</th>'+''.join('<th>'+esc(p['name'])+'</th>' for p in P)+'</tr></thead><tbody>'+''.join('<tr><th>'+esc(label)+'</th>'+''.join('<td>'+esc(value)+'</td>' for value in values)+'</tr>' for label,values in rows)+'</tbody></table></div>'
seo_graph=''.join(f'<div class="sp-scope-row"><span>{esc(p["name"])}</span><div><i style="width:{p["seo"]["pages"]*100/60:.2f}%"></i></div><b>{fa(p["seo"]["pages"])} صفحه</b></div>' for p in P)
seo_layers='<div class="sp-layers"><article><span>01 / طراحی سالم</span><h3>در همه پلن‌ها</h3><p>طراحی اختصاصی، گوشی، URL پایدار، تصویر سبک، امنیت و کنترل سند. پلن اول بسته تحقیق، تنظیم و اجرای اختصاصی سئو ندارد.</p></article><article><span>02 / پایه‌گذاری سئو</span><h3>پلن‌های دوم تا چهارم</h3><p>تحقیق کلمه و رقبا، فنی کامل، ابزار سنجش، اصلاح دستی ۲۰، ۴۰ یا ۶۰ URL و دو، چهار یا شش راهنمای مستند اولیه.</p></article><article><span>03 / هدف صفحه اول</span><h3>عملیات ماهانه جدا</h3><p>بهبود بر اساس داده گوگل، گسترش مدل/دسته/کاربرد و محتوای واقعی، سنجش تماس واجد شرایط؛ هدف Top 10 برای فهرست مشخص کلمات، بدون وعده رتبه و زمان قطعی.</p></article></div>' 
monthly_cards=''.join(f'<article class="sp-monthly-card"><span class="kicker">خدمات ماهانه</span><h3>{esc(m["name"])}</h3><b>{fa(m["price"])} <small>میلیون / ماه</small></b><div class="sp-monthly-counts"><span>{fa(m["pages"])} صفحه</span><span>{fa(m["articles"])} راهنما</span><span>{fa(m["hours"])} ساعت اصلاح فنی</span></div><p>{esc(m["scope"])}</p></article>' for m in D['monthly'][1:])
addons=''.join(f'<article class="sp-addon"><div><h3>{esc(a["name"])}</h3><b>{fa(a["price"])} میلیون</b></div><p>{esc(a["description"])}</p></article>' for a in D['addons'])
payment=''.join(f'<article><b>{fa(percent)}٪</b><h3>{esc(label)}</h3></article>' for label,percent in D['payments'])
steps=[('۱ · نیاز و نمونه داده','دریافت نمونه CSV، شمارش مدل/تنوع، بررسی قیمت و واحد؛ تأیید طراحی اختصاصی، قوانین سند و مقصد ایمیل.'),('۲ · طرح و کاتالوگ','تأیید یک خانه، محصول و لیست نمونه؛ تکمیل طرح منتخب و ورود ۳۰۰ SKU آماده. توضیح کوتاه و جدول واقعی، بدون متن ساختگی.'),('۳ · سند، امنیت و سئو','صدور فوری PDF با قیمت سرور، ایمیل و کنترل دسترسی؛ سپس بسته سئو فقط مطابق پلن و محتوای فنی پس از تأیید متخصص.'),('۴ · پذیرش و انتشار','ثبت سناریو سند/قیمت/ایمیل/امنیت/بازیابی، اصلاحات، انتشار و آموزش فروش؛ قرارداد ماهانه و مسئول عملیات جدا مشخص می‌شود.')]
timeline='<div class="sp-timeline">'+''.join('<article><span>'+esc(title)+'</span><p>'+esc(text)+'</p></article>' for title,text in steps)+'</div>'
budget=f'''<div class="sp-budget"><form id="sp-budget-form"><div class="sp-budget-fields"><label>پلن ساخت<select name="plan">{''.join('<option value="'+p['id']+'"'+(' selected' if p['id']=='commerce' else '')+'>'+esc(p['name'])+' · '+fa(p['price'])+' میلیون</option>' for p in P)}</select></label><label>خدمات ماهانه<select name="monthly">{''.join('<option value="'+m['id']+'">'+esc(m['name'])+' · '+fa(m['price'])+' میلیون</option>' for m in D['monthly'])}</select></label><label>دوره بودجه‌بندی<select name="months">{''.join('<option value="'+str(n)+'"'+(' selected' if n==6 else '')+'>'+fa(n)+' ماه</option>' for n in [3,6,12])}</select></label><label>بودجه رسانه ماهانه<select name="media"><option value="0">بدون تخصیص فعلی</option><option value="10">۱۰ میلیون</option><option value="20">۲۰ میلیون</option><option value="30">۳۰ میلیون</option></select></label><label>SKU آماده اضافه<select name="sku"><option value="0">همان مبنای موقت ۳۰۰ SKU</option>{''.join('<option value="'+str(n)+'">'+fa(n*100)+' SKU اضافه · '+fa(n*next(a['price'] for a in D['addons'] if a['id']=='sku'))+' میلیون</option>' for n in [1,2,3])}</select></label></div><div class="sp-budget-checks"><label><input type="checkbox" name="bale">بات بله برای یک مقصد فروش · ۶ میلیون</label><label><input type="checkbox" name="foundation">پایه‌گذاری سئو بعد از پلن اول · ۱۵ میلیون</label><label><input type="checkbox" name="language">زبان دوم با ترجمه آماده · ۱۸ میلیون</label><label><input type="checkbox" name="pdf">یک قالب PDF اضافه · ۵ میلیون</label><label><input type="checkbox" name="maintenance">فقط نگهداری مستقل · ۵ میلیون در ماه</label></div><p id="sp-foundation-note"></p><p id="sp-maintenance-note">در انتخاب خدمات سئوی ماهانه، نگهداری پایه داخل همان مبلغ است.</p></form><aside class="sp-budget-result" aria-live="polite" aria-atomic="true"><span>برآورد دامنه انتخاب‌شده</span><div><b id="sp-budget-total">۷۰</b><small>میلیون تومان</small></div><dl><dt>ساخت و گزینه‌های یک‌باره</dt><dd id="sp-budget-setup">۷۰</dd><dt>دستمزد ماهانه</dt><dd id="sp-budget-monthly">۰</dd><dt>رسانه ماهانه</dt><dd id="sp-budget-media">۰</dd><dt>دوره</dt><dd id="sp-budget-period">۶ ماه</dd></dl><p id="sp-budget-equation">۷۰ + ۶ × (۰ + ۰) = ۷۰</p><small>هاست، مجوز، SMTP، API، ترجمه، بازبین فنی مستقل در نبود متخصص کارفرما و مالیات احتمالی جدا هستند. محاسبه پیشنهاد بودجه است و سفارش ثبت نمی‌کند.</small></aside></div><noscript><p class="sp-note">نمونه بودجه: ساخت با پایه‌گذاری ۷۰ + شش ماه رشد حرفه‌ای ۳۵ = ۲۸۰ میلیون؛ رسانه و سرویس‌ها جدا.</p></noscript>'''

body=section('project-scope','نیاز واقعی مشتری، مبنای این پیشنهاد','<div class="sp-layers"><article><span>طراحی</span><h3>اختصاصی؛ بدون دمو</h3><p>وودمارت و المنتور با چیدمان منتخب جدید؛ مدیریت قیمت همچنان در ووکامرس برای فروش ساده می‌ماند.</p></article><article><span>فروش</span><h3>تماس و سند فوری</h3><p>۳۰۰ SKU مبنای موقت؛ بدون حساب مشتری و درگاه. قیمت معتبر ثبت‌شده، پیش‌فاکتور فوری، ایمیل و گزینه اعلان بله.</p></article><article><span>اعتماد و رشد</span><h3>امنیت و محتوای واقعی</h3><p>امنیت مشترک همه پلن‌ها؛ هدف صفحه اول برای کلمات منتخب، با برنامه مستمر و مقاله علمی دارای منبع/بازبین.</p></article></div><p class="sp-note">این نسخه نیاز جدید کارفرما را جایگزین فرض حساب مشتری و سقف ۱۵۰ SKU کرده است؛ تعداد واقعی محصولات هنوز باید از فایل کالا مشخص شود.</p>','بازنگری بر اساس نیاز')
body+=section('quote-flow','مشتری بدون ثبت‌نام چگونه سند و راه تماس می‌گیرد؟','<div class="sp-timeline"><article><span>۱ · مدل و مقدار</span><p>کالای قیمت‌دار انتخاب می‌شود؛ واحد و مقدار مجاز معلوم است. کالای بدون قیمت به فروش وصل می‌شود.</p></article><article><span>۲ · قیمت معتبر سرور</span><p>نام/موبایل و ایمیل اختیاری؛ قیمت لحظه صدور دوباره بررسی می‌شود. اختلاف قیمت نیاز به تأیید تازه دارد.</p></article><article><span>۳ · PDF و ایمیل</span><p>سند شماره‌دار با snapshot و لینک دارای انقضا؛ ایمیل فروش و نسخه مشتری در صورت درخواست. اعلان بله گزینه اضافه است.</p></article><article><span>۴ · تماس فروش</span><p>شماره تماس کنار سند و محصول؛ فروش وضعیت تماس را ثبت می‌کند و قیمت/تأمین/حمل نهایی را هماهنگ می‌کند.</p></article></div><div class="sp-related"><a href="security.html">جزئیات امنیت ↗</a><a href="#addons">دامنه بات بله ↗</a></div>','مسیر اصلی تبدیل')
body+=section('choose','چهار پلن، با مرز کار و خروجی مشخص','<div class="sp-status"><strong>پیشنهاد قابل ارائه · ۱۸ مهر ۱۴۰۵</strong><span>قیمت‌ها پس از تأیید اطلاعات واقعی کارفرما نهایی می‌شوند.</span></div><div class="sp-plan-grid">'+cards+'</div>','انتخاب سطح اجرا')
body+=section('compare','تفاوت پلن‌ها؛ طراحی و امنیت مشترک است',matrix+'<p class="sp-note">همه پلن‌ها طراحی اختصاصی و صدور فوری سند دارند. تفاوت اصلی، دامنه پایه‌گذاری سئو و پوشش اولیه محتواست. درگاه و حساب مشتری در هیچ‌کدام نیست؛ سئوی ماهانه جدا سفارش داده می‌شود.</p>','مقایسه دامنه')
body+=section('seo-in-design','در مبلغ طراحی چه مقدار سئو انجام می‌شود؟',seo_layers+'<div class="sp-scope-chart">'+seo_graph+'</div><details class="sp-detail"><summary>الزامات طراحی سالم؛ حتی بدون بسته سئو</summary>'+ul(D['common']['سازگاری فنی پایه حتی بدون بسته سئو'])+'</details><details class="sp-detail"><summary>پایه‌گذاری کامل سئو در پلن‌های دوم تا چهارم</summary>'+ul(P[1]['features']['پایه‌گذاری سئو'])+'</details><p class="sp-note"><strong>صفحه منتخب یعنی کار دستی مشخص روی یک URL.</strong> تعداد هر پلن مجموع نهایی است و مقاله‌ها جدا شمارش می‌شوند. ۳۰۰ کالا ورود داده دارند، اما همه آن‌ها توضیح اختصاصی/تحقیق سئو دریافت نمی‌کنند. پلن اول صفر خروجی اختصاصی سئو دارد؛ طراحی سالم به معنی خرید خدمات سئو نیست.</p><div class="sp-related"><a href="seo-roadmap.html#keyword-playbook">نقشه کلمه به صفحه ↗</a><a href="competitors.html#competitors">فرصت رقبا ↗</a><a href="seo-roadmap.html#measurement">سنجش تماس و نتیجه ↗</a></div>','سه لایه مشخص')
body+=section('details','شرح کامل هر پلن','<div class="sp-detail-toolbar"><p>یک پلن را از کارت‌ها انتخاب کنید؛ تمام جزئیات و مرزهای همان پلن اینجا آمده است.</p><button class="btn btn-secondary" type="button" id="sp-show-all" hidden>نمایش جزئیات همه پلن‌ها</button></div>'+''.join(detail(p,i+1) for i,p in enumerate(P)),'تعهدات و پذیرش')
body+=section('scientific-content','محتوای فنی دقیق؛ نه توضیح طولانی برای هر کالا',ul(P[1]['features']['کیفیت علمی و اصالت محتوا'])+'<div class="sp-timeline"><article><span>منبع اولیه</span><p>دیتاشیت سازنده، مستند استاندارد یا پژوهش علمی با نسخه و تاریخ؛ داده واقعی برند و مدل.</p></article><article><span>تحلیل برای خریدار</span><p>جدول، مثال و محدودیت کاربرد؛ به اندازه نیاز و بدون ادعای تجربه ساختگی یا تعداد کلمه اجباری.</p></article><article><span>بازبینی متخصص</span><p>واحد، عدد، شرایط نصب و نتیجه بررسی می‌شود؛ نام بازبین واقعی و هزینه مستقل در صورت نیاز مشخص است.</p></article><article><span>انتشار و اصلاح</span><p>پس از تأیید، اتصال به مدل/دسته و تماس؛ بازنگری با تغییر منبع یا داده واقعی، نه تغییر صوری تاریخ.</p></article></div><p class="sp-note">تعداد راهنماهای ماهانه برای کیفیت تخصصی تنظیم شده است: دو، چهار یا شش راهنما. AI ابزار کمک است؛ انتشار مقاله حساس بدون تأیید فنی انجام نمی‌شود.</p>','استاندارد تحریریه')
body+=section('first-page-plan','هدف صفحه اول؛ برای چه کلمه و با چه سنجشی؟','<div class="sp-layers"><article><span>اولویت اولیه</span><h3>مدل، برند و قصد خرید</h3><p>کلماتی مانند خرید + مدل واقعی یا تأمین + کاربرد؛ صفحه متناسب با همان قصد و تماس واضح. نمایندگی تنها با مدرک.</p></article><article><span>توسعه تدریجی</span><h3>دسته و کاربرد</h3><p>پس از داده کافی، رقابت روی دسته‌ها و راهنماهای پرتقاضا؛ اصلاح تجربه تماس و پوشش فنی کمبود رقبا.</p></article><article><span>گزارش نتیجه</span><h3>Top 10 و تماس باکیفیت</h3><p>فهرست کلمات/URL، کشور و دستگاه مشخص؛ کنار رتبه، کلیک و درخواست واجد شرایط گزارش می‌شود. کلیک تلفن فروش نیست.</p></article></div><p class="sp-note">صفحه اول هدف برنامه است؛ رتبه و زمان آن تعهد قطعی قرارداد نیست. خدمات ماهانه بر خروجی و اقدام مشخص بسته می‌شود؛ فهرست کلمات پس از مشاهده سبد و تحلیل رقابت نهایی خواهد شد.</p><div class="sp-related"><a href="seo-roadmap.html#roadmap">نقشه شش‌ماهه کامل ↗</a><a href="competitors.html#competitors">تحلیل رقبا ↗</a></div>','مسیر رشد قابل سنجش')
body+=section('monthly','بعد از تحویل، چه کارهایی ماهانه انجام می‌شود؟','<div class="sp-monthly-grid">'+monthly_cards+'</div><details class="sp-detail" open><summary>مرز خدمات ماهانه و روش گزارش</summary>'+ul(D['monthlyNotes'])+'</details><p class="sp-note">نگهداری مستقل بدون خرید سئو: <strong>۵ میلیون در ماه</strong>؛ همان نگهداری پایه با سقف سه ساعت اصلاح فنی کوچک، بدون تولید محتوا یا توسعه قابلیت جدید. منابع و کیفیت اطلاعات فنی باید توسط کارفرما یا کارشناس معرفی‌شده تأیید شوند.</p>','خدمات پس از طراحی')
body+=section('addons','گزینه‌های مستقل؛ بله، کالا و پایه‌گذاری بعدی','<div class="sp-addon-grid">'+addons+'</div><p class="sp-note">ایمیل فروش در همه پلن‌هاست. بات بله برای یک مقصد داخلی فروش افزوده می‌شود؛ مشتری مجبور به ساخت حساب یا نصب پیام‌رسان نیست. پایه‌گذاری ۱۵ میلیونی فقط برای پلن اول است و در پلن‌های دوم تا چهارم دوباره محاسبه نمی‌شود.</p>','دامنه اختیاری')
body+=section('budget','بودجه ساخت و چند ماه خدمات را کنار هم حساب کنید',budget,'محاسبه تعاملی')
body+=section('delivery','مراحل اجرا، پرداخت و مسئول هر ورودی',timeline+'<div class="sp-payment">'+payment+'</div><div class="sp-note"><strong>تحویل قابل سنجش:</strong> معیارهای عمومی و معیارهای هر پلن در نسخه آزمایشی ثبت می‌شوند. تصمیم نهایی درباره انتشار با کارفرماست. شروع روزهای کاری به دریافت داده و تأیید دامنه وابسته است؛ تأخیر و تغییر نیاز در برنامه مشترک ثبت می‌شود.</div>','برنامه تحویل')
body+=section('boundaries','پیش از قرارداد، این موارد باید روشن شوند','<div class="sp-boundary-grid"><details class="sp-detail" open><summary>فرض‌های قیمت</summary>'+ul(D['assumptions'])+'</details><details class="sp-detail" open><summary>هزینه‌ها و پروژه‌های خارج از قیمت</summary>'+ul(D['outside'])+'</details></div><div class="sp-note">نصب افزونه جای معیار پذیرش نیست. در همه پلن‌ها اطلاعات خصوصی باید با کنترل مجوز محافظت شوند؛ noindex یا مخفی‌کردن منو حفاظت دسترسی نیست. ارتقای پلن پیش از شروع با اختلاف قیمت انجام می‌شود؛ پس از شروع، کار انجام‌شده و نیاز به بازسازی جدا برآورد می‌شوند.</div>','تعریف مرزها')
body+=section('references','مبنای فنی و فایل‌های قابل تحویل','<div class="sp-related">'+''.join('<a href="'+url+'" target="_blank" rel="noopener">'+esc(title)+' ↗</a>' for title,url in D['sources'])+'</div><p class="sp-note">این‌ها منابع اصول فنی‌اند؛ قیمت‌ها برآورد پیشنهادی همین پروژه هستند و تعرفه رسمی وردپرس یا گوگل محسوب نمی‌شوند. ادعای پیشی‌گرفتن از رقبا یا رتبه قطعی در پیشنهاد نیست.</p><div class="sp-related"><a href="service-plans-proposal.md" download>دانلود شرح تمام پلن‌ها ↓</a><a href="service-plans.json" download>فایل ساختاریافته پلن‌ها ↓</a><a href="client-brief.html">تکمیل اطلاعات کارفرما ←</a><a href="build-paths.html#compare">بازگشت به مسیر ساخت ←</a></div>','منابع و خروجی')
doc=f'''<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="چهار پلن دقیق اجرای فروشگاه کابل با وردپرس، وودمارت و المنتور؛ قیمت، سئوی داخل طراحی، امکانات فروش، معیار تحویل و بودجه ماهانه."><title>پلن‌ها، قیمت و دامنه سئو | گزارش سایت کابل</title><link rel="stylesheet" href="reports-site.css"><link rel="stylesheet" href="service-plans.css?v=plans-2"></head><body class="service-plans"><nav class="site-nav" aria-label="ناوبری اصلی"><div class="wrap"><a class="site-brand" href="index.html"><span class="brand-mark" aria-hidden="true">◎</span><span>پرونده بازار کابل</span></a>{nav}<div class="nav-actions"><button class="icon-btn print-btn" type="button" id="sp-print">چاپ شرح پلن‌ها</button><button class="icon-btn" id="theme-toggle" type="button" aria-label="تغییر تم">☀</button></div></div><div class="reading-bar" id="reading-bar" aria-hidden="true"></div></nav><header class="hero sp-hero"><div class="wrap"><div><span class="eyebrow">پیشنهاد اجرایی · وردپرس / وودمارت / المنتور</span><h1>هر مبلغ، <em>چه خروجی‌ای دارد؟</em></h1><p>دامنه طراحی، امکانات فروش، سئوی زمان ساخت و کار ماهانه را برای هر سطح دقیق ببینید؛ طراحی اختصاصی، تماس و پیش‌فاکتور بدون حساب، با سئوی قابل سفارش جدا.</p><div class="hero-actions"><a class="primary" href="#compare">مقایسه چهار پلن ←</a><a class="secondary" href="#seo-in-design">سئو داخل طراحی</a><a class="secondary" href="#budget">بودجه کل</a></div></div><div class="hero-art"><img src="assets/editorial-2026/build-v1.webp" fetchpriority="high" width="1536" height="1024" alt="تصویر مفهومی مسیر ساخت سایت کابل"></div></div></header><main class="wrap page-main">{body}</main><footer class="site-footer"><div class="wrap"><strong>پلن‌ها و دامنه اجرای سایت کابل</strong><span>۱۰ اکتبر ۲۰۲۶ · پیشنهاد برای تصمیم؛ پس از تکمیل داده‌ها نهایی می‌شود</span></div></footer><button class="toc-fab" id="toc-fab" type="button" aria-expanded="false" aria-controls="toc-panel">فهرست بخش‌ها</button><nav class="toc-panel" id="toc-panel" aria-label="فهرست همین صفحه" hidden><strong>در این صفحه</strong></nav><script src="reports-site.js"></script><script id="sp-data" type="application/json">{json.dumps(D,ensure_ascii=False).replace('<','\\u003c')}</script><script src="service-plans.js?v=plans-2"></script></body></html>'''
doc=doc.replace('<meta name="viewport"','<meta name="robots" content="noindex,nofollow,noarchive"><meta name="viewport"',1)
(PRIVATE/'service-plans.html').write_text(doc,encoding='utf-8')

def plain(p):
    s=p['seo']
    lines=[f"پلن {p['name']} — {fa(p['price'])} میلیون تومان",D['status'],f"زمان پیشنهادی: {p['days']} روز کاری",'','دامنه طراحی',p['design'],'',f"سئوی داخل ساخت: {fa(s['pages'])} صفحه منتخب، {fa(s['articles'])} مقاله آغاز، {fa(s['clusters'])} خوشه",s['description'],s['followup'],'']
    for k,v in {**D['common'],**features(p)}.items():lines.extend([k,*['- '+x for x in v],''])
    lines.extend(['معیارهای پذیرش',*['- '+x for x in acceptance_for(p)],'','اجزای قیمت',*['- '+label+': '+fa(value)+' میلیون' for label,value in p['breakdown']],f"جمع: {fa(p['price'])} میلیون",'','خارج از این پلن',*['- '+x for x in p['excluded']],'','فرض‌های مشترک',*['- '+x for x in D['assumptions']],'','هزینه‌های بیرونی',*['- '+x for x in D['outside']],'','مراحل پرداخت',*['- '+label+': '+fa(percent)+'٪' for label,percent in D['payments']],'','خدمات ماهانه (جدا از ساخت)'])
    for m in D['monthly'][1:]:lines.extend([m['name']+': '+fa(m['price'])+' میلیون در ماه',m['scope']])
    lines.extend(['',*['- '+x for x in D['monthlyNotes']],'','گزینه‌های اضافه'])
    for a in D['addons']:lines.extend([a['name']+': '+fa(a['price'])+' میلیون',a['description']])
    lines.extend(['','نگهداری مستقل بدون سئو: ۵ میلیون در ماه؛ داخل پلن ماهانه دوباره دریافت نمی‌شود.','منابع',*[title+': '+url for title,url in D['sources']]])
    return '\n'.join(lines)+'\n'
for p in P:(PRIVATE/f"service-plan-{p['id']}.txt").write_text(plain(p),encoding='utf-8-sig')
(PRIVATE/'service-plans-proposal.md').write_text('# پیشنهاد تفصیلی اجرای فروشگاه کابل\n\n'+ '\n\n---\n\n'.join(plain(p) for p in P),encoding='utf-8')
from visual_upgrade import upgrade_page
upgrade_page(PRIVATE/'service-plans.html')
from shutil import copyfile
for name in ['service-plans.html','service-plans.json','service-plans-proposal.md',*[f"service-plan-{p['id']}.txt" for p in P]]:
    if PRIVATE != ROOT: copyfile(PRIVATE/name,ROOT/name)
print('Created four detailed plans, SEO scope, monthly services and proposal files.')
