from pathlib import Path

ROOT = Path(__file__).parent
NAV = [('index.html','نقشه راه'),('competitors.html','رقبا'),('strategy.html','راهبرد'),('build-paths.html','مسیر ساخت'),('design.html','طراحی'),('templates.html','تمپلیت‌ها'),('woodmart-templates.html','وودمارت'),('security.html','امنیت'),('seo-roadmap.html','سئو')]
STEPS = [
    ('discovery','شناخت و تصمیم','دیدن رقبا و پیدا کردن فرصت‌ها','اول سایت‌های مشابه را ببینیم؛ بعد عمق اطلاعات کالا، طراحی، سئو و مسیر استعلام آن‌ها را مقایسه کنیم.','فهرست رقبا و فرصت‌هایی که سایت ما باید پوشش دهد.','competitors.html#screenshots','دیدن رقبا و تصاویر', [('competitors.html#competitors','نقشه رقابت'),('competitors.html#start-here','خلاصه بررسی')]),
    ('strategy','شناخت و تصمیم','تعیین راهبرد و ساختار سایت','مشخص کنیم مشتری چگونه مدل کابل را پیدا می‌کند، چه مدرکی لازم دارد و کدام اقلام خرید آنلاین یا استعلامی‌اند.','اولویت صفحات، اطلاعات هر مدل و روش فروش.','strategy.html#priorities','تعیین اولویت‌های سایت', [('strategy.html','گزارش راهبرد'),('design.html#journey','مسیر خریدار'),('design.html#next','داده‌های لازم')]),
    ('seo','شناخت و تصمیم','چیدن برنامه سئو از شروع پروژه','نوع سبد و روش فروش را انتخاب کنیم و نقشه کلمه، صفحه و محتوا را پیش از ساخت مشخص کنیم. تجربه دیپلم‌سرا هم در گزارش آمده است.','صفحات هدف، خوشه‌های محتوا و برنامه شش‌ماهه.','seo-roadmap.html#paths','انتخاب مسیر سئو', [('seo-roadmap.html#case-study','نمونه دیپلم‌سرا'),('seo-roadmap.html#keyword-playbook','کلمه و صفحه'),('seo-roadmap.html#roadmap','برنامه شش‌ماهه')]),
    ('design','طراحی و اجرا','انتخاب شکل سایت و تمپلیت وودمارت','طرح‌های خانه، فهرست کالا، محصول، درباره، تماس و حساب را ببینیم و یک هویت منسجم برای اجرای المنتور انتخاب کنیم.','طرح منتخب و اجزای قابل اجرای آن در وودمارت.','woodmart-templates.html#gallery','دیدن طرح‌های وودمارت', [('design.html','منطق طراحی'),('templates.html','گالری تمپلیت‌ها'),('woodmart-templates.html#customer-pages','صفحات مشتری')]),
    ('build','طراحی و اجرا','مشخص کردن مسیر ساخت و مدیریت فروش','برای انتخاب فعلیِ وردپرس، اجرای وودمارت، المنتور و ووکامرس را به کارهای مشخص تبدیل کنیم؛ توسعه اختصاصی برای نیازهای اضافه بررسی شود.','دامنه اجرای نسخه اول، ابزارها و مسئول مدیریت کالا/قیمت.','build-paths.html#routes','دیدن مراحل ساخت', [('woodmart-templates.html#implementation','اجرای المنتور'),('woodmart-templates.html#pricing','مدیریت قیمت'),('build-paths.html#ai-editorial','محتوا با n8n و AI')]),
    ('security','طراحی و اجرا','طراحی امنیت، ورود و پیش‌فاکتور مشتری','دسترسی کارکنان، کد ورود، سند خصوصی، نسخه قیمت و برنامه بازیابی را پیش از فعال‌کردن حساب و فروش تعیین کنیم.','قواعد دسترسی، گردش سند و معیار پذیرش قابلیت‌ها.','security.html#security-plan','انتخاب مسیر امنیت', [('security.html#login','ورود و بازیابی'),('security.html#quotes','پیش‌فاکتور خصوصی'),('security.html#acceptance','معیار پذیرش')]),
    ('launch','راه‌اندازی و رشد','تحویل، راه‌اندازی و بهبود مستمر','پس از آماده‌شدن صفحات و داده واقعی، معیارهای تحویل بررسی شوند؛ سپس جست‌وجو، استعلام و فروش مبنای اصلاح ماهانه قرار بگیرند.','نسخه قابل تحویل، مسئول نگه‌داری و گزارش رشد.','seo-roadmap.html#measurement','برنامه سنجش و رشد', [('security.html#delivery','مراحل تحویل'),('security.html#operations','نگه‌داری و بازیابی'),('seo-roadmap.html#deliverables','تحویل‌های سئو')]),
]

def step_html(i, step):
    slug, phase, title, text, output, url, cta, links = step
    number = str(i).translate(str.maketrans('0123456789','۰۱۲۳۴۵۶۷۸۹'))
    next_link = f'<a class="rm-next" href="#step-{STEPS[i][0]}">مرحله بعد: {STEPS[i][2]} ↓</a>' if i < len(STEPS) else '<a class="rm-next" href="#start-here">بازگشت به ابتدای مسیر ↑</a>'
    return f'''<li class="rm-step" id="step-{slug}"><span class="rm-number" aria-label="مرحله {number}">{number}</span><article class="rm-step-card"><div class="rm-step-copy"><span class="rm-phase">{phase}</span><h3>{title}</h3><p>{text}</p><div class="rm-output"><strong>خروجی این مرحله</strong><span>{output}</span></div></div><div class="rm-step-links"><a class="btn btn-primary" href="{url}">{cta} ←</a><div class="rm-connections">{''.join(f'<a href="{href}">{label} ↗</a>' for href,label in links)}</div>{next_link}</div></article></li>'''

nav = ''.join(f'<a href="{href}"'+(' aria-current="page"' if href=='index.html' else '')+f'>{label}</a>' for href,label in NAV)
short_labels = ['دیدن رقبا', 'راهبرد سایت', 'برنامه سئو', 'انتخاب طرح', 'مسیر ساخت', 'امنیت و فروش', 'راه‌اندازی و رشد']
phase_links = ''.join(f'<a href="#step-{s[0]}"><span>{i:02}</span>{short_labels[i-1]}</a>' for i,s in enumerate(STEPS,1))
directory = ''.join(f'<a href="{href}"><span>{label}</span><b aria-hidden="true">↗</b></a>' for href,label in NAV[1:])
html = f'''<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="نقشه راه ساخت سایت کابل: بررسی رقبا، راهبرد، سئو، طرح وودمارت، ساخت، امنیت و برنامه راه‌اندازی؛ پیوند مرحله‌به‌مرحله به همه گزارش‌ها."><title>نقشه راه سایت کابل | از بررسی رقبا تا اجرا و رشد</title><link rel="stylesheet" href="reports-site.css"><link rel="stylesheet" href="roadmap-home.css?v=roadmap-1"></head><body class="home-page roadmap-home">
<nav class="site-nav" aria-label="ناوبری اصلی"><div class="wrap"><a class="site-brand" href="index.html"><span class="brand-mark" aria-hidden="true">◎</span><span>پرونده بازار کابل</span></a><div class="nav-links">{nav}</div><div class="nav-actions"><button class="icon-btn" id="theme-toggle" type="button" aria-label="تغییر تم">☀</button></div></div><div class="reading-bar" id="reading-bar" aria-hidden="true"></div></nav>
<header class="hero hub-hero"><div class="wrap"><div><span class="eyebrow">نقشه راه پروژه · ۷ مرحله به ترتیب</span><h1>نقشه راه سایت کابل؛<br><em>از رقبا تا اجرا و رشد.</em></h1><p>این صفحه نقطه شروع پرونده است. هر مرحله یک تصمیم را روشن می‌کند و شما را به گزارش، طرح یا برنامه اجرایی مرتبط می‌رساند.</p><div class="hero-meta"><span>مسیر منتخب: وردپرس و وودمارت</span><span>کابل وارداتی و برندهای داخلی</span></div><div class="hero-actions"><a class="primary" href="#step-discovery">شروع از دیدن رقبا ←</a><a class="secondary" href="#reports">همه گزارش‌ها</a></div></div><div class="hero-art hub-hero-art"><img src="assets/cable-market-editorial.webp" alt="تصویر مفهومی کابل و قرقره صنعتی" fetchpriority="high"><div class="hero-photo-label"><span>نقشه راه سایت کابل</span><strong>شناخت ← طراحی ← رشد</strong><small>هر تصمیم، متصل به گزارش خودش</small></div></div></div></header>
<main class="wrap page-main"><section class="rm-overview" id="start-here"><div class="rm-overview-copy"><div class="kicker">مسیر در یک نگاه</div><h2>به ترتیب جلو بروید؛ به هر بخش هم مستقیم دسترسی دارید</h2><p>ابتدا بازار و صفحات هدف را بشناسیم، سپس طرح و اجرای سایت را مشخص کنیم و در پایان تحویل و رشد را پیگیری کنیم. امنیت و سئو از شروع طراحی در تصمیم‌ها حضور دارند.</p></div><div class="rm-phases"><a href="#step-discovery"><span>۰۱–۰۳</span><b>شناخت و تصمیم</b><small>رقبا · راهبرد · سئو</small></a><a href="#step-design"><span>۰۴–۰۶</span><b>طراحی و اجرا</b><small>تمپلیت · ساخت · امنیت</small></a><a href="#step-launch"><span>۰۷</span><b>راه‌اندازی و رشد</b><small>تحویل · سنجش · نگه‌داری</small></a></div></section>
<section class="section" id="project-roadmap"><div class="section-head"><div><div class="kicker">نقشه راه به ترتیب</div><h2>در هر مرحله، چه تصمیمی می‌گیریم؟</h2><p>لینک اصلی هر مرحله شما را به نقطه شروع همان کار می‌برد؛ لینک‌های کناری، جزئیات مرتبط را باز می‌کنند.</p></div></div><nav class="rm-shortcuts" aria-label="انتخاب مرحله">{phase_links}</nav><ol class="rm-steps">{''.join(step_html(i,s) for i,s in enumerate(STEPS,1))}</ol><aside class="rm-note"><strong>وضعیت فعلی پرونده</strong><p>گزارش‌ها و نمونه‌های طراحی برای تصمیم‌گیری آماده‌اند. نام برندها، مدل‌ها و قواعد واقعی فروش هنوز باید تکمیل شوند؛ ورود، قیمت و پیش‌فاکتور نمونه‌ها نمایشی‌اند. اجرای وردپرس و اتصال سرویس‌ها در مرحله پیاده‌سازی انجام می‌شود.</p></aside></section>
<section class="section" id="reports"><div class="section-head"><div><div class="kicker">ارتباط با تمام صفحات پرونده</div><h2>دسترسی مستقیم به گزارش‌ها</h2><p>اگر بخش موردنظر را می‌دانید، از اینجا مستقیم باز کنید.</p></div></div><div class="rm-directory">{directory}</div></section>
<section class="section evidence-feature" id="visual-evidence"><div class="evidence-feature-copy"><div class="kicker">پیشنهاد شروع</div><h2>قبل از انتخاب طرح، رقبا را ببینید</h2><p>۱۰ سایت مرتبط در گزارش بررسی شده‌اند؛ ۱۸ تصویر دسکتاپ و گوشی از ۹ سایت، مشاهده شکل صفحات را آسان می‌کنند.</p><a class="btn btn-primary" href="competitors.html#screenshots">دیدن اطلس رقبا ←</a></div><div class="evidence-mosaic" aria-label="پیش‌نمایش تصاویر رقبا"><a href="competitors.html#shot-barghsan"><img src="competitor-screenshots/barghsan-desktop.jpg" alt="صفحه اصلی برق‌سان" loading="lazy"><span>برق‌سان</span></a><a href="competitors.html#shot-voltatadbir"><img src="competitor-screenshots/voltatadbir-desktop.jpg" alt="صفحه اصلی ولتا تدبیر" loading="lazy"><span>ولتا تدبیر</span></a><a href="competitors.html#shot-legrandco"><img src="competitor-screenshots/legrandco-desktop.jpg" alt="صفحه اصلی لگراندکو" loading="lazy"><span>لگراندکو</span></a></div></section>
</main><footer class="site-footer"><div class="wrap"><strong>نقشه راه سایت کابل · پرونده پروژه</strong><span>۱۱ مهر ۱۴۰۵ · از بررسی رقبا تا تحویل و رشد</span></div></footer><button class="toc-fab" id="toc-fab" type="button" aria-expanded="false" aria-controls="toc-panel">فهرست مرحله‌ها</button><nav class="toc-panel" id="toc-panel" aria-label="فهرست همین صفحه" hidden><strong>در این صفحه</strong></nav><script src="reports-site.js"></script></body></html>'''
(ROOT/'index.html').write_text(html,encoding='utf-8')
print('Roadmap homepage generated')
