from pathlib import Path

ROOT=Path(__file__).parent
NAV=[('index.html','اصلی'),('competitors.html','رقبا'),('strategy.html','راهبرد'),('build-paths.html','مسیر ساخت'),('design.html','طراحی'),('templates.html','تمپلیت‌ها'),('woodmart-templates.html','وودمارت'),('security.html','امنیت'),('seo-roadmap.html','سئو')]

def report(filename,title,description,eyebrow,hero,lead,meta,image,body,script=''):
    links=''.join(f'<a href="{url}"'+(' aria-current="page"' if url==filename else '')+f'>{name}</a>' for url,name in NAV)
    doc=f'''<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{description}"><title>{title}</title><link rel="stylesheet" href="reports-site.css"><link rel="stylesheet" href="implementation-reports.css?v=studio-4"></head><body>
<nav class="site-nav" aria-label="ناوبری اصلی"><div class="wrap"><a class="site-brand" href="index.html"><span class="brand-mark" aria-hidden="true">◎</span><span>پرونده بازار کابل</span></a><div class="nav-links">{links}</div><div class="nav-actions"><button class="icon-btn print-btn" type="button" onclick="window.print()">چاپ / PDF</button><button class="icon-btn" id="theme-toggle" type="button" aria-label="تغییر تم">☀</button></div></div><div class="reading-bar" id="reading-bar" aria-hidden="true"></div></nav>
<header class="hero"><div class="wrap"><div><span class="eyebrow">{eyebrow}</span><h1>{hero}</h1><p>{lead}</p><div class="hero-meta">{''.join('<span>'+m+'</span>' for m in meta)}</div><div class="hero-actions"><a class="primary" href="#start-here">از اینجا شروع کنید ←</a><a class="secondary" href="woodmart-templates.html#gallery">طرح‌های وودمارت</a></div></div><div class="hero-art"><img src="{image}" alt="تصویر مفهومی کابل برای گزارش اجرایی"></div></div></header>
<main class="wrap page-main">{body}</main><footer class="site-footer"><div class="wrap"><strong>{title}</strong><span>۱ اکتبر ۲۰۲۶ · برنامه پیشنهادی؛ اجرای واقعی پس از تعیین داده و زیرساخت</span></div></footer><button class="toc-fab" id="toc-fab" type="button" aria-expanded="false" aria-controls="toc-panel">فهرست بخش‌ها</button><nav class="toc-panel" id="toc-panel" aria-label="فهرست همین صفحه" hidden><strong>در این صفحه</strong></nav><script src="reports-site.js"></script>{script}</body></html>'''
    (ROOT/filename).write_text(doc,encoding='utf-8')

SECURITY='''
<section class="ir-intro" id="start-here"><div><div class="kicker">امنیت همراه تجربه مشتری</div><h2>حساب مشخص، سند خصوصی، عملیات قابل پیگیری</h2><p>مشتری از سایت عمومی کالا را پیدا می‌کند؛ پس از ورود، فقط درخواست‌ها و پیش‌فاکتورهای خودش را می‌بیند. فروش قیمت‌گذاری و صدور سند را انجام می‌دهد و مدیر فنی امنیت، دسترسی و بازیابی را نگه می‌دارد.</p></div><aside><strong>وضعیت این خروجی:</strong> گزارش و نمونه رابط HTML است. هیچ تنظیم امنیتی روی وردپرس، سرویس OTP یا پایگاه‌داده واقعی اعمال نشده است؛ داده‌های پنل نمایشی‌اند.</aside></section>
<nav class="ir-jump" aria-label="بخش‌های امنیت"><a href="#layers">امنیت وردپرس</a><a href="#login">ورود ایمیل / پیامک</a><a href="#customer">حساب مشتری</a><a href="#quotes">پیش‌فاکتورها</a><a href="#roles">دسترسی‌ها</a><a href="#operations">نگه‌داری</a><a href="#delivery">مراحل اجرا</a></nav>
<section class="section" id="layers"><div class="section-head"><div><div class="kicker">۰۱ / امنیت در چند لایه</div><h2>وودمارت ظاهر را می‌سازد؛ امنیت در کل سامانه اجرا می‌شود</h2><p>کنترل‌ها را بین میزبانی، وردپرس، افزونه‌ها و داده خصوصی تقسیم می‌کنیم تا مسئول هر بخش مشخص باشد.</p></div></div><div class="ir-flow"><article><small>01 / HOST</small><b>میزبانی و شبکه</b><p>HTTPS، نسخه‌های پشتیبانی‌شده سرور، WAF متناسب و پشتیبان مستقل.</p></article><article><small>02 / WORDPRESS</small><b>هسته و افزونه‌ها</b><p>به‌روزرسانی هماهنگ، افزونه‌های ضروری و دسترسی محدود به فایل‌ها.</p></article><article><small>03 / ACCESS</small><b>ورود و مجوز</b><p>ورود دومرحله‌ای مدیران، نشست امن و کنترل مجوز هر عملیات.</p></article><article><small>04 / PRIVATE DATA</small><b>حساب و اسناد</b><p>مالکیت سند، دانلود محافظت‌شده و ثبت تغییر قیمت و وضعیت.</p></article></div>
<div class="ir-table"><table><thead><tr><th>بخش</th><th>اقدام اجرایی</th><th>مسئول و محل اجرا</th></tr></thead><tbody>
<tr><td>نسخه و مجوز</td><td>WoodMart و افزونه‌ها از منبع معتبر و با مجوز تهیه شوند؛ نسخه‌های ناشناس کنار گذاشته شوند. تغییر در Child theme یا افزونه اختصاصی باشد، تا به‌روزرسانی فایل اصلی را بازنویسی نکند.</td><td>مجری / مدیریت قالب <a href="https://xtemos.com/docs-topic/update-the-theme/" target="_blank" rel="noopener">مرجع به‌روزرسانی وودمارت ↗</a></td></tr>
<tr><td>به‌روزرسانی</td><td>فهرست نسخه‌ها، پشتیبان پیش از تغییر و محیط staging جدا. هسته، WoodMart Core، WooCommerce و Elementor هماهنگ به‌روز شوند؛ خرید، ورود و استعلام جزو معیار تحویل تغییر هستند.</td><td>نگه‌داری فنی؛ اصلاح آسیب‌پذیری مهم با اولویت روزانه، بررسی عادی هفتگی.</td></tr>
<tr><td>مدیریت وردپرس</td><td>حساب شخصی برای هر مدیر، گذرواژه یکتا و مدیر رمز، ورود دومرحله‌ای با TOTP/کلید امنیتی در راهکار منتخب. نقش مدیر کل به افراد ضروری محدود شود؛ حساب مشترک ایجاد نشود.</td><td>ادمین؛ یک راهکار امنیت/ورود با قابلیت موردنیاز، پس از بررسی سازگاری.</td></tr>
<tr><td>سرور و فایل</td><td>HTTPS سراسری، دسترسی فایل متناسب با میزبان، حفاظت از تنظیمات و کلیدها، غیرفعال کردن ویرایش فایل در پیشخوان با DISALLOW_FILE_EDIT. REST API و wp-admin با قواعدی که خرید و افزونه‌ها را مختل نکنند محافظت شوند.</td><td>هاست و مجری؛ مقدار مجوز فایل و قواعد WAF برای همان سرور تعیین شود.</td></tr>
<tr><td>کش فروشگاه</td><td>حساب، سبد، پرداخت، ورود و endpoints پیش‌فاکتور از کش عمومی/CDN خارج باشند. پاسخ دانلود خصوصی Cache-Control متناسب داشته باشد؛ کش نباید اطلاعات یک مشتری را به دیگری بدهد.</td><td>مجری؛ هماهنگی افزونه کش، وب‌سرور و CDN.</td></tr>
<tr><td>فرم و فایل پیوست</td><td>اعتبارسنجی سمت سرور، محدودیت اندازه/نوع واقعی فایل و اسکن مناسب. BOM و اسناد مشتری در مسیر خصوصی نگه‌داری شوند؛ محدودیت نام فایل یا پسوند به‌تنهایی کافی نیست.</td><td>افزونه RFQ/فرم یا افزونه اختصاصی <a href="https://cheatsheetseries.owasp.org/cheatsheets/File_Upload_Cheat_Sheet.html" target="_blank" rel="noopener">مرجع آپلود امن ↗</a></td></tr>
</tbody></table></div><details class="ir-details"><summary>پشته پیشنهادی افزونه‌ها برای شروع اجرا</summary><div class="ir-grid ir-grid-two"><article class="ir-card"><h3>حفاظت و ورود مدیران</h3><p>Wordfence Security یک گزینه برای WAF برنامه و ورود دومرحله‌ای TOTP مدیران است. نسخه رایگان و پولی، زمان دریافت قواعد متفاوت دارند؛ انتخاب با بودجه و سطح پشتیبانی انجام شود. WAF پس از دوره یادگیری و بررسی درخواست‌های سالم تنظیم شود.</p></article><article class="ir-card"><h3>ورود و اسناد مشتری</h3><p>برای OTP فقط یک افزونه متصل به درگاه پیامک منتخب و ایمیل تراکنشی انتخاب شود. Quote for WooCommerce گزینه بررسی برای پیش‌فاکتور است؛ نقش فروش، اسناد سازمانی و گردش تأیید ممکن است توسعه اختصاصی بخواهند.</p></article><article class="ir-card"><h3>پشتیبان و ارسال ایمیل</h3><p>پشتیبان مستقل میزبان یا یک راهکار پشتیبان با مخزن خارج از سرور، به‌همراه یک اتصال SMTP/API معتبر. گزارش شکست ارسال و امکان بازیابی سند و سفارش جزو تحویل باشد.</p></article><article class="ir-card"><h3>سازگاری با وودمارت</h3><p>فرم ورود سفارشی، Elementor، endpoints حساب، کش و خرید در محیط staging بررسی شوند. وجود افزونه امنیتی جای کنترل مالکیت پیش‌فاکتور را نمی‌گیرد؛ دو افزونه با نقش تکراری بدون نیاز نصب نشوند.</p></article></div><div class="ir-source-row"><a href="https://www.wordfence.com/help/firewall/" target="_blank" rel="noopener">راهنمای WAF وردفنس ↗</a><a href="https://www.wordfence.com/help/tools/two-factor-authentication/" target="_blank" rel="noopener">TOTP و سازگاری فرم ورود ↗</a></div></details><div class="ir-source-row"><a href="https://developer.wordpress.org/advanced-administration/security/hardening/" target="_blank" rel="noopener">راهنمای رسمی امن‌سازی وردپرس ↗</a><a href="https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html" target="_blank" rel="noopener">اصول احراز هویت OWASP ↗</a></div></section>

<section class="section" id="login"><div class="section-head"><div><div class="kicker">۰۲ / ورود کم‌اصطکاک</div><h2>ایمیل یا پیامک؛ هر دو به یک مشتری متصل شوند</h2><p>ظاهر فرم در Login/Register Layout وودمارت قابل طراحی است. ارسال و تأیید کد، پیش‌فرض قالب نیست و افزونه سازگار یا سرویس اختصاصی می‌خواهد.</p></div></div><div class="ir-grid ir-grid-two"><article class="ir-card"><small>EMAIL LOGIN</small><h3>مسیر ایمیل</h3><p>ورود با ایمیل و گذرواژه، مسیر پایه ووکامرس است. برای ایمیل بدون گذرواژه، کد کوتاه‌عمر یا لینک ورود یک‌بارمصرف توسط افزونه/سرویس اجرا شود. SMTP/API قابل اعتماد برای ارسال و ثبت خطا در نظر گرفته شود.</p><ul><li>لینک فقط HTTPS و با توکن تصادفی یک‌بارمصرف.</li><li>ایمیل فقط پس از تأیید مالکیت به حساب متصل شود.</li><li>بازیابی دسترسی و تغییر ایمیل به تأیید مجدد نیاز داشته باشد.</li></ul></article><article class="ir-card"><small>SMS LOGIN</small><h3>مسیر پیامک</h3><p>افزونه OTP سازگار با سرویس پیامک انتخاب شود؛ هزینه ارسال، پایداری، قالب پیام و پشتیبانی شماره‌های هدف معیار انتخاب‌اند. کلید سرویس در سرور نگه‌داری شود.</p><ul><li>کد کوتاه‌عمر، یک‌بارمصرف و به درخواست همان ورود متصل.</li><li>محدودیت ارسال برای شماره و IP و محدودیت تلاش تأیید.</li><li>تغییر شماره فقط پس از تأیید؛ ادغام حساب با تشابه نام انجام نشود.</li></ul></article></div>
<div class="ir-flow"><article><small>01 / IDENTITY</small><b>شناسه ورود</b><p>ایمیل یا شماره استانداردشده؛ پاسخ عمومی بدون افشای وجود حساب.</p></article><article><small>02 / CHALLENGE</small><b>ارسال و محدودیت</b><p>پیشنهاد پروژه: اعتبار ۲ دقیقه، فاصله ارسال ۶۰ ثانیه، سقف تلاش ۵ بار؛ قابل تنظیم پس از داده واقعی.</p></article><article><small>03 / VERIFICATION</small><b>تأیید در سرور</b><p>کد به‌صورت امن نگه‌داری، مصرف و سپس باطل شود؛ کد یا کلید سرویس در مرورگر و لاگ ذخیره نشود.</p></article><article><small>04 / SESSION</small><b>نشست مشتری</b><p>نشست معتبر وردپرس، احراز مالکیت حساب و ورود به محتوای همان مشتری.</p></article></div>
<div class="ir-note"><strong>تفکیک مدیر و مشتری:</strong> ورود آسان مشتری با SMS جایگزین MFA حساب مدیر نیست. شماره تلفن می‌تواند جابه‌جا یا بازیافت شود؛ عملیات حساس مثل تغییر شناسه، دسترسی سازمانی و دانلود داده زیاد، تأیید مجدد و کنترل ریسک می‌خواهد. پارامترهای بالا پیشنهاد طراحی‌اند، معیار قطعی امنیت نیستند.</div><div class="ir-linkboard"><a href="woodmart-slider-render.html?theme=wave&page=login"><b>ورود در موج</b><span>ایمیل و پیامک؛ پیش‌نمایش</span></a><a href="woodmart-slider-render.html?theme=pulse&page=login"><b>ورود در پالس</b><span>ایمیل و پیامک؛ پیش‌نمایش</span></a><a href="woodmart-slider-render.html?theme=orbit&page=login"><b>ورود در مدار</b><span>ایمیل و پیامک؛ پیش‌نمایش</span></a></div><div class="ir-source-row"><a href="https://xtemos.com/docs-topic/my-account-page-builder/" target="_blank" rel="noopener">My account و Login/Register Layout ↗</a><a href="https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html" target="_blank" rel="noopener">مدیریت نشست OWASP ↗</a></div></section>

<section class="section" id="customer"><div class="section-head"><div><div class="kicker">۰۳ / حساب حقیقی و حقوقی</div><h2>حساب قابل استفاده برای هر مشتری</h2><p>داشبورد، درخواست‌ها و پیش‌فاکتورها بخش نخست‌اند؛ سفارش‌ها، نشانی‌ها و اطلاعات حساب از endpoints ووکامرس استفاده می‌کنند. برای سازمان چندکاربره، عضویت و اجازه نماینده شرکت جدا تعریف شود.</p></div></div><div class="ir-grid"><article class="ir-card"><small>STANDARD</small><h3>مشتری تکی</h3><p>یک شناسه customer_user_id، ایمیل/تلفن تأییدشده و اسناد متصل به همان شناسه. صفحه حساب با My account navigation و My account content ساخته شود.</p></article><article class="ir-card"><small>B2B ORGANIZATION</small><h3>شرکت با چند کاربر</h3><p>company_id و عضویت تأییدشده، نقش درخواست‌کننده/تأییدکننده و دسترسی به اسناد شرکت. ایمیل هم‌دامنه به‌تنهایی اجازه مشاهده اسناد شرکت ایجاد نکند.</p></article><article class="ir-card"><small>GUEST REQUEST</small><h3>مشتری بدون حساب</h3><p>ثبت درخواست عمومی ممکن است؛ اتصال به حساب پس از تأیید هویت انجام شود. ایمیل تایپ‌شده در فرم، مالکیت سند را ثابت نمی‌کند.</p></article></div><div class="ir-linkboard"><a href="woodmart-slider-render.html?theme=wave&page=account"><b>پنل موج</b><span>داشبورد و اسناد</span></a><a href="woodmart-slider-render.html?theme=pulse&page=account"><b>پنل پالس</b><span>داشبورد و اسناد</span></a><a href="woodmart-slider-render.html?theme=orbit&page=account"><b>پنل مدار</b><span>داشبورد و اسناد</span></a></div><div class="ir-note"><strong>اجرای پیشنهادی:</strong> WoodMart → Layouts → My account برای ظاهر؛ افزونه RFQ برای endpoint پیش‌فاکتورها؛ افزونه اختصاصی سبک فقط برای نیازهای تکمیلی مالکیت، نسخه سند یا پنل فروش. سازگاری hooks افزونه با Layout سفارشی باید در مرحله اجرا تأیید شود. درباره ما و تماس با المنتور ساخته می‌شوند.</div></section>

<section class="section" id="quotes"><div class="section-head"><div><div class="kicker">۰۴ / گردش سند</div><h2>از درخواست مشتری تا پیش‌فاکتور نسخه‌دار</h2><p>درخواست RFQ، پیش‌فاکتور و سفارش سه رکورد با نقش‌های متفاوت‌اند. مبلغ صادرشده به همان نسخه تعلق دارد و با تغییر قیمت عمومی کالا بازنویسی نمی‌شود.</p></div></div><div class="ir-flow"><article><small>REQUEST</small><b>درخواست</b><p>SKU، مقدار، واحد، مقصد، موعد و توضیح؛ بدون صدور قیمت توسط مشتری.</p></article><article><small>SALES REVIEW</small><b>بررسی فروش</b><p>تأیید مدل و موجودی، قیمت و شرایط؛ ثبت مسئول پاسخ.</p></article><article><small>ISSUED QUOTE</small><b>صدور نسخه</b><p>شماره سند، مشتری، مبلغ ثابت، تاریخ اعتبار و شرایط مالی/تحویل.</p></article><article><small>ACCEPT / ORDER</small><b>تصمیم مشتری</b><p>تأیید نسخه معتبر؛ تبدیل به سفارش در سرور پس از بازبینی قیمت و تأمین.</p></article></div>
<div class="ir-table"><table><thead><tr><th>گروه داده</th><th>فیلدهای لازم</th><th>قاعده</th></tr></thead><tbody><tr><td>مالکیت و نسخه</td><td>quote_id، customer_user_id، company_id اختیاری، revision، status، issued_at، expires_at، created_by</td><td>مالکیت فقط سمت سرور؛ هر اصلاح بعد از صدور نسخه جدید بسازد.</td></tr><tr><td>ردیف کالا</td><td>SKU/variation_id، نام و ویژگی‌ها در لحظه صدور، مقدار، واحد، قیمت واحد، تخفیف مجاز</td><td>قیمت سند snapshot است؛ قیمت مرجع محصول جدا نگه‌داری می‌شود.</td></tr><tr><td>شرایط</td><td>ارز، روش محاسبه مالیات، هزینه حمل یا وضعیت تعیین‌نشده، اعتبار، موعد و شرایط پرداخت</td><td>تومان/ریال یکپارچه؛ مبلغ نهایی بدون قاعده واقعی ساخته نشود.</td></tr><tr><td>پیگیری</td><td>رویداد تغییر، نسخه قبلی، کاربر، زمان، توضیح و ارتباط با RFQ/order</td><td>تأیید مشتری به همان نسخه متصل؛ سند منقضی قابل پذیرش یا پرداخت نباشد.</td></tr><tr><td>فایل</td><td>شناسه فایل خصوصی، checksum، نسخه سند، اجازه دانلود</td><td>PDF در اجرای واقعی از اطلاعات نسخه ساخته شود؛ آدرس عمومی uploads برای سند خصوصی کافی نیست.</td></tr></tbody></table></div>
<div class="ir-grid ir-grid-two" style="margin-top:20px"><article class="ir-card"><small>PLUGIN ROUTE</small><h3>مسیر افزونه RFQ</h3><p>نمونه قابل بررسی: Quote for WooCommerce در بازار رسمی ووکامرس. مستندات آن فهرست Quotes در My account، اعتبار و تبدیل به سفارش را توضیح می‌دهد. قبل از انتخاب، نسخه، زبان فارسی، تومان، PDF، نقش‌ها و اتصال به Layout وودمارت بررسی شوند؛ خرید افزونه در این گزارش انجام نشده است.</p><a href="https://woocommerce.com/document/quote-for-woocommerce-store-owners-guide-basic-concepts/" target="_blank" rel="noopener">مستندات افزونه نمونه ↗</a></article><article class="ir-card"><small>CUSTOM EXTENSION ROUTE</small><h3>مسیر افزونه اختصاصی</h3><p>وقتی سند چندنسخه‌ای، دسترسی شرکتی، تأیید چندمرحله‌ای یا اتصال ERP پیچیده باشد، منطق در افزونه اختصاصی قرار گیرد. المنتور ظاهر را ویرایش می‌کند؛ مجوز، مبلغ و وضعیت روی سرور اجرا می‌شوند.</p><a href="woodmart-build-brief.md" download>شرح اجرای پروژه ↓</a></article></div>
<details class="ir-details"><summary>قانون دسترسی به یک پیش‌فاکتور</summary><p>در هر مشاهده، دانلود، تأیید و تبدیل به سفارش: ابتدا نشست معتبر؛ سپس اجازه عملیاتی؛ بعد تطبیق مالک سند با کاربر یا عضویت مجاز شرکت؛ سپس اعتبار نسخه و وضعیت. شناسه سند از URL قابل تغییر است و نباید مجوز ایجاد کند.</p><p>REST endpoint سفارشی باید permission_callback مناسب داشته باشد. nonce برای مقابله با CSRF به کار می‌رود و جای احراز هویت و کنترل مجوز را نمی‌گیرد. فایل فقط بعد از همان کنترل‌های دسترسی تحویل شود.</p><div class="ir-source-row"><a href="https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/" target="_blank" rel="noopener">احراز هویت REST ↗</a><a href="https://developer.wordpress.org/apis/security/nonces/" target="_blank" rel="noopener">محدودیت‌های nonce ↗</a><a href="https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html" target="_blank" rel="noopener">کنترل مجوز OWASP ↗</a></div></details></section>

<section class="section" id="roles"><div class="section-head"><div><div class="kicker">۰۵ / مسئولیت‌ها</div><h2>هر فرد، دسترسی متناسب با کارش</h2></div></div><div class="ir-table"><table><thead><tr><th>نقش</th><th>اجازه</th><th>محدودیت</th></tr></thead><tbody><tr><td>مشتری</td><td>درخواست، مشاهده اسناد خود، تأیید نسخه معتبر، سفارش خود</td><td>قیمت‌گذاری، سند دیگران و تنظیمات سایت ممنوع.</td></tr><tr><td>نماینده شرکت</td><td>عملیات تعیین‌شده برای اسناد company_id تأییدشده</td><td>مجوز عضویت و سقف تأیید، به‌صورت مستقل تعریف شود.</td></tr><tr><td>کارشناس فروش</td><td>پاسخ RFQ و تهیه/صدور سند در محدوده تعیین‌شده</td><td>نیازمند نقش سفارشی؛ نصب افزونه و تغییر امنیت مجاز نباشد.</td></tr><tr><td>مسئول قیمت</td><td>ویرایش قیمت از پنل محدود، با رویداد قیمت قبلی/جدید</td><td>Shop Manager گسترده‌تر از این کار است؛ فقط پنهان کردن منو کافی نیست.</td></tr><tr><td>مدیر محتوا و سئو</td><td>صفحه و مقاله، مشخصات تأییدشده، متادیتا و پیوندها</td><td>اسناد خصوصی و قیمت‌گذاری خارج از محدوده؛ نقش سفارشی در صورت نیاز.</td></tr><tr><td>مدیر فنی</td><td>به‌روزرسانی، پشتیبان، نقش‌ها و تنظیمات سرویس</td><td>MFA، ثبت تغییر و حساب جدا؛ استفاده روزانه با نقش محدودتر.</td></tr></tbody></table></div><div class="ir-source-row"><a href="https://woocommerce.com/document/roles-capabilities/" target="_blank" rel="noopener">دامنه نقش‌های اصلی ووکامرس ↗</a><a href="woodmart-templates.html#pricing">نمونه میز مدیریت قیمت ←</a></div></section>

<section class="section" id="operations"><div class="section-head"><div><div class="kicker">۰۶ / استمرار سرویس</div><h2>امنیت بعد از راه‌اندازی ادامه دارد</h2></div></div><div class="ir-grid"><article class="ir-card"><small>BACKUP / RESTORE</small><h3>بازیابی قابل اجرا</h3><p>پیشنهاد شروع: پشتیبان کامل روزانه خارج از هاست، نسخه افزایشی پایگاه‌داده اسناد ساعتی و نگه‌داری ۳۰روزه. بازیابی دوره‌ای روی محیط جدا انجام شود. هدف اولیه پیشنهادی: از دست رفتن حداکثر ۱ ساعت داده سند و بازیابی در ۴ ساعت؛ امکان واقعی با هاست و هزینه تعیین می‌شود.</p></article><article class="ir-card"><small>MONITOR / AUDIT</small><h3>رویداد و هشدار</h3><p>خطای OTP، تلاش ورود، دسترسی ردشده به سند، تغییر قیمت/نسخه و خطای سفارش ثبت شود. لاگ شامل کد OTP، رمز، کلید API و متن کامل اطلاعات مالی مشتری نباشد؛ نگه‌داری و دسترسی لاگ محدود شود.</p></article><article class="ir-card"><small>INCIDENT</small><h3>روال رخداد</h3><p>تشخیص و ثبت → محدود کردن دسترسی آسیب‌دیده → حفظ شواهد → تعویض دسترسی‌های لازم → رفع علت → بازیابی و بازبینی اسناد تغییرکرده. مسئول پاسخ و راه ارتباط اضطراری قبل از انتشار تعیین شوند.</p></article></div><div class="ir-note"><strong>حریم خصوصی:</strong> فقط داده لازم جمع شود؛ مالیات و مدارک هویتی مشتری در فضای عمومی یا ابزارهای تحلیل ارسال نشوند. رصد SEO رویدادهایی مثل quote_submit را بدون نام، موبایل و مبلغ خصوصی ثبت کند. صفحات عمومی سئو و فایل‌های فنی مجاز از اسناد مالی خصوصی جدا هستند.</div></section>

<section class="section" id="delivery"><div class="section-head"><div><div class="kicker">۰۷ / اجرای مرحله‌ای</div><h2>تحویل امنیت و حساب، در چهار مرحله</h2></div></div><div class="ir-steps"><article class="ir-step"><span>مرحله ۱</span><div><h3>پایه سایت و نقش‌ها</h3><p>دامنه/HTTPS، staging خصوصی، قالب معتبر، پشتیبان، نقش‌ها و MFA مدیران.</p><span class="ir-owner">مسئول: مجری + هاست</span><div class="ir-output">خروجی: نقشه دسترسی و روش بازیابی مکتوب.</div></div></article><article class="ir-step"><span>مرحله ۲</span><div><h3>ورود و حساب مشتری</h3><p>انتخاب سرویس ایمیل/پیامک، روش اتصال شناسه‌ها، Layout حساب و قواعد نشست.</p><span class="ir-owner">مسئول: مجری + مالک سرویس پیام‌رسان</span><div class="ir-output">خروجی: جریان ثبت‌نام، ورود، بازیابی و تغییر شناسه.</div></div></article><article class="ir-step"><span>مرحله ۳</span><div><h3>پیش‌فاکتور و فروش</h3><p>مالکیت سند، نسخه، اعتبار، PDF خصوصی، رویدادها و تبدیل کنترل‌شده به سفارش.</p><span class="ir-owner">مسئول: توسعه‌دهنده + فروش</span><div class="ir-output">خروجی: گردش سند کامل برای دو مشتری با مالکیت مستقل.</div></div></article><article class="ir-step"><span>مرحله ۴</span><div><h3>آموزش و نگه‌داری</h3><p>سناریوهای ورود ناموفق، دسترسی غیرمجاز، سند منقضی، بازیابی و قطع سرویس پیامک جزو معیار پذیرش اجرای واقعی باشند.</p><span class="ir-owner">مسئول: مجری + مسئول فروش + نگه‌داری</span><div class="ir-output">خروجی: آموزش، قرارداد نگه‌داری و مسئول پاسخ رخداد.</div></div></article></div><div class="ir-linkboard"><a href="woodmart-templates.html#gallery"><b>ظاهر پنل‌ها</b><span>هفت صفحه در هر طرح جدید</span></a><a href="seo-roadmap.html#technical"><b>امنیت و سئوی فنی</b><span>عمومی و خصوصی، کش و ایندکس</span></a><a href="build-paths.html"><b>مسیرهای ساخت</b><span>وردپرس و توسعه اختصاصی</span></a></div></section>
'''

SEO='''
<section class="ir-intro" id="start-here"><div><div class="kicker">تصمیم اصلی سئو</div><h2>صفحه‌ای بسازیم که خریدار کابل واقعاً به آن نیاز دارد</h2><p>مزیت پیشنهادی: مدل دقیق، مشخصات قابل استناد، واحد و وضعیت تأمین روشن، مقایسه کاربردی و استعلام متصل به همان کالا. طراحی زیبا و افزونه سئو، زیرساخت این تجربه‌اند؛ کیفیت داده و پاسخ به نیاز خریدار مسیر رشد را تعیین می‌کند.</p></div><aside><strong>داده فعلی:</strong> برندها، SKUها و بازار مشتری هنوز مشخص نیستند. مسیرهای زیر جداگانه‌اند؛ مثال کلمات و حجم تولید، پیشنهاد برنامه‌اند و حجم جست‌وجو یا پیش‌بینی ترافیک نیستند. یافته رقبا از گزارش ۲۷ سپتامبر ۲۰۲۶ است.</aside></section>
<nav class="ir-jump" aria-label="بخش‌های سئو"><a href="#paths">انتخاب مسیر</a><a href="#competitor-opportunities">فرصت‌های رقبا</a><a href="#architecture">نقشه صفحات</a><a href="#technical">سئوی وردپرس</a><a href="#roadmap">برنامه شش‌ماهه</a><a href="#content">محتوا و AI</a><a href="#measurement">سنجش نتیجه</a><a href="#deliverables">تحویل‌ها</a></nav>

<section class="section" id="paths"><div class="section-head"><div><div class="kicker">۰۱ / هر احتمال، یک برنامه</div><h2>نوع کالا و مدل فروش را انتخاب کنید</h2><p>چهار مسیر کالا با سه مدل فروش ترکیب می‌شوند. کارهای مشترک ثابت‌اند؛ صفحه هدف، داده لازم، محتوا و رویداد تبدیل با انتخاب شما تغییر می‌کنند.</p></div></div><div class="ir-selector"><fieldset><legend>۱. اگر سبد شرکت این باشد…</legend><div class="ir-choices" data-choice-group="sector"><button data-value="industrial" aria-pressed="true">کابل صنعتی و خاص</button><button data-value="network" aria-pressed="false">شبکه و وارداتی</button><button data-value="domestic" aria-pressed="false">برندهای داخلی</button><button data-value="mixed" aria-pressed="false">سبد ترکیبی / پروژه‌ای</button></div></fieldset><fieldset><legend>۲. اگر روش فروش این باشد…</legend><div class="ir-choices" data-choice-group="sales"><button data-value="quote" aria-pressed="true">کاتالوگ و استعلام</button><button data-value="online" aria-pressed="false">قیمت و خرید آنلاین</button><button data-value="hybrid" aria-pressed="false">خرید + استعلام</button></div></fieldset><div class="ir-route-result" id="seo-route-result" aria-live="polite"></div></div><div class="ir-note"><strong>برای شروع از کلمات عمومی استفاده نکنیم:</strong> ابتدا مدل‌ها و خانواده‌هایی که واقعاً قابل تأمین‌اند، تقاضای مرتبط دارند و تیم فروش می‌تواند پاسخ دهد. «خرید کابل» هدف بلندمدت است؛ اولویت اولیه با تقاطع برند، مدل، کاربرد و وضعیت واقعی عرضه است.</div></section>

<section class="section" id="competitor-opportunities"><div class="section-head"><div><div class="kicker">۰۲ / از مشاهده به اجرا</div><h2>از گزارش رقبا، کار قابل تحویل استخراج کنیم</h2><p>این جدول مقایسه ترافیک و رتبه نیست. هر مشاهده به کارت رقیب و سپس اقدام پیشنهادی متصل شده است؛ وضعیت امروز تمام سایت‌های رقیب دوباره اندازه‌گیری نشده است.</p></div></div><div class="ir-table"><table><thead><tr><th>رقیب / نشانه</th><th>آنچه در گزارش دیده شد</th><th>کار ما</th><th>اولویت</th></tr></thead><tbody>
<tr><td>ولتا تدبیر</td><td>معرفی برند و خانواده صنعتی پررنگ است؛ مسیر کد/مقایسه در نمونه بررسی‌شده روشن نبود. <a href="competitors.html#analysis-voltatadbir-seo">شاهد و ارزیابی ←</a></td><td>صفحه مدل قابل خزش، SKU و کد سازنده، جدول مشخصات و استعلام همان کد؛ راهنمای خانواده به مدل لینک دهد.</td><td>صنعتی / P0</td></tr>
<tr><td>مانیاد صنعت</td><td>صفحه تخصصی و کاتالوگ دارد؛ ناوبری عمیق و یک واحد فنی نیازمند بازبینی گزارش شده است. <a href="competitors.html#analysis-maniadsanat-seo">شاهد و ارزیابی ←</a></td><td>اطلاعات فنی از دیتاشیت سازنده، بازبین مشخص، تاریخ و واحد دقیق؛ دسترسی خانواده → مدل و جست‌وجوی کد.</td><td>صنعتی / P0</td></tr>
<tr><td>رایا ارتباط نیروانا</td><td>کد و ویژگی کالا و دغدغه اصالت واردات مطرح شده‌اند. <a href="competitors.html#analysis-renirvana-seo">شاهد و ارزیابی ←</a></td><td>صفحه برند/مدل با پارت‌نامبر واقعی، روش بررسی اصالت و مدارک مجاز هر کالا؛ ادعای نمایندگی فقط با مدرک.</td><td>شبکه / P0</td></tr>
<tr><td>لگراندکو</td><td>دسته دارای راهنما و مدل‌های نزدیک است؛ متن انگلیسی پیش‌فرض در محتوای بررسی‌شده دیده شد. <a href="competitors.html#analysis-legrandco-seo">شاهد و ارزیابی ←</a></td><td>فارسی‌سازی کامل UI و متن، مقایسه مدل‌ها و بسته‌بندی، صفحه دسته مفید با کالاهای واقعی.</td><td>شبکه / P1</td></tr>
<tr><td>برق‌سان</td><td>محصول دارای مشخصات و دیتاشیت؛ فرم پیش‌فاکتور با متن آزاد اقلام. <a href="competitors.html#analysis-barghsan-sales">شاهد و ارزیابی ←</a></td><td>همان عمق محصول + RFQ چندردیفی استاندارد؛ اندازه‌گیری ارسال استعلام واجد اطلاعات، به تفکیک صفحه ورودی.</td><td>همه / P0</td></tr>
<tr><td>برق و صنعت آسیا</td><td>فهرست گسترده و پیش‌فاکتور دارد؛ واحد متری برای چند قلم غیرمتری دیده شد. <a href="competitors.html#analysis-bargheasia-sales">شاهد و ارزیابی ←</a></td><td>واحد صحیح، مبلغ قابل نگه‌داری، متر/حلقه/بسته مستقل و کنترل هماهنگی داده در صفحه و schema.</td><td>فروش آنلاین / P0</td></tr>
<tr><td>کابل ایران</td><td>دسته و فیلترهای متنوع برای جست‌وجوی عمومی. <a href="competitors.html#analysis-cableiran-seo">شاهد و ارزیابی ←</a></td><td>تمرکز روی چند خوشه واقعی؛ صفحات دسته منتخب با تقاضا، کنترل ترکیب‌های فیلتر و جلوگیری از هزاران صفحه کم‌ارزش.</td><td>سبد گسترده / P1</td></tr>
<tr><td>جهان کابل آرکا</td><td>جزئیات فنی مفصل و نشانه‌های نگه‌داری/اطلاعات نمونه در صفحات گزارش. <a href="competitors.html#analysis-jahancablearka-seo">شاهد و ارزیابی ←</a></td><td>بازبینی مشخصات، تماس واقعی، نویسنده/بازبین معتبر و نشانی پایدار؛ تغییر URL با نگاشت انتقال انجام شود.</td><td>داخلی / P1</td></tr>
<tr><td>لگراند پارس / چلیپا</td><td>در اولی لینک محتوای نامرتبط دیده شد؛ برای دومی دامنه مستقل قابل ارزیابی قطعی نبود. <a href="competitors.html#analysis-legrandpars-seo">لگراند پارس ←</a> <a href="competitors.html#analysis-chalipacable-seo">محدودیت چلیپا ←</a></td><td>دامنه مرجع پایدار، صفحات قابل دسترس، محتوای تخصصی مرتبط و پیوند داخلی سالم. محدودیت مشاهده به معنی ضعف رتبه نیست.</td><td>همه / P0</td></tr>
</tbody></table></div><div class="ir-source-row"><a href="competitors.html#screenshots">اطلس تصویری رقبا ←</a><a href="competitive-audit-2026-09-27.md">گزارش مبنا و محدودیت‌ها ←</a></div></section>

<section class="section" id="architecture"><div class="section-head"><div><div class="kicker">۰۳ / معماری جست‌وجو</div><h2>هر قصد جست‌وجو، یک صفحه مرجع</h2><p>از دسته به مدل لینک قابل خزش بدهیم و راهنمای انتخاب را به کالای موجود وصل کنیم. صفحه اصلی دروازه دسته‌ها و خدمات است؛ متن حجیم همه کلمات روی خانه قرار نگیرد.</p></div></div><div class="ir-architecture"><div><small>CATEGORY / BUYING INTENT</small><b>خانواده محصول</b><p>دامنه کاربرد، تفاوت گزینه‌ها، فیلتر مفید، واحد فروش و محصولات مرتبط.</p><code>/product-category/control-cables/</code></div><div><small>BRAND / SUPPLIER INTENT</small><b>برند قابل تأمین</b><p>خانواده‌های واقعی، وضعیت نمایندگی مستند، راهنمای مدل و شرایط تأمین.</p><code>/brand/[verified-brand]/</code></div><div><small>MODEL / EXACT INTENT</small><b>مدل یا پارت‌نامبر</b><p>نام دقیق، مشخصات، عکس واقعی، منبع دیتاشیت، واحد و خرید/استعلام همان مدل.</p><code>/product/[model-code]/</code></div><div><small>GUIDE / RESEARCH INTENT</small><b>راهنمای انتخاب</b><p>پرسش واقعی خریدار، محدودیت‌ها، منبع و لینک به مدل‌های مرتبط.</p><code>/guides/[selection-topic]/</code></div><div><small>COMPARISON / DECISION</small><b>مقایسه مدل‌ها</b><p>تفاوت واقعی با داده فنی، شرایط کاربرد و لینک به دو صفحه مدل؛ صرفاً تعویض اسم نیست.</p><code>/compare/[model-a]-[model-b]/</code></div><div><small>SUPPLY / PROJECT INTENT</small><b>خدمات تأمین پروژه</b><p>نوع نیاز، مراحل بررسی، مدارک مجاز، شرایط و RFQ ساختاریافته.</p><code>/services/project-supply/</code></div></div>
<div class="ir-grid ir-grid-two"><article class="ir-card"><small>ONE PRODUCT / ONE PRIMARY URL</small><h3>مدل و گزینه را درست جدا کنیم</h3><p>برای مدل‌های با هویت جست‌وجوی متفاوت صفحه مستقل؛ برای اندازه‌های یک مدل، محصول متغیر با ویژگی و SKU گزینه‌ها. صفحات پارامتر، رنگ یا اندازه بدون ارزش مستقل به کاتالوگ تکراری تبدیل نشوند؛ canonical و راهبرد variant بر اساس ساختار واقعی تعیین شود.</p></article><article class="ir-card"><small>PUBLIC / PRIVATE</small><h3>محتوای عمومی و حساب خصوصی</h3><p>قیمت عمومی معتبر و اطلاعات فنی قابل انتشار در صفحه کالا. حساب، سبد و اسناد خصوصی در sitemap نباشند؛ noindex جای حفاظت دسترسی را نمی‌گیرد. دیتاشیت سازنده فقط با اجازه انتشار عمومی و در کنار HTML توضیح‌دار قرار گیرد.</p></article></div><div class="ir-note"><strong>شهرها و زبان‌ها:</strong> تا شعبه، خدمت یا مدرک محلی واقعی نداریم، برای ده‌ها شهر صفحات با متن یکسان نسازیم. انگلیسی فقط در صورت بازار واقعی و توان نگه‌داری، با URL و ترجمه مستقل و hreflang صحیح؛ نسخه صرفاً ماشینی بدون کنترل فنی منتشر نشود.</div><div class="ir-source-row"><a href="https://developers.google.com/search/docs/specialty/ecommerce/help-google-understand-your-ecommerce-site-structure" target="_blank" rel="noopener">معماری فروشگاه در گوگل ↗</a><a href="https://developers.google.com/search/docs/specialty/ecommerce/designing-a-url-structure-for-ecommerce-sites" target="_blank" rel="noopener">ساختار URL فروشگاهی ↗</a></div></section>

<section class="section" id="technical"><div class="section-head"><div><div class="kicker">۰۴ / WordPress + WoodMart + Elementor</div><h2>زیرساخت سئو را پیش از انبوه محتوا آماده کنیم</h2></div></div><div class="ir-table"><table><thead><tr><th>موضوع</th><th>اقدام پیشنهادی</th><th>معیار تحویل</th></tr></thead><tbody>
<tr><td>افزونه سئو</td><td>یک افزونه اصلی؛ پیشنهاد پایه Rank Math یا در صورت انتخاب قبلی Yoast. عنوان، توضیح، canonical، sitemap و تنظیم محتوای قابل ایندکس. قابلیت پولی فقط وقتی داده و نیاز آن وجود دارد.</td><td>یک منبع هماهنگ متادیتا و schema؛ نمره سبز افزونه معیار موفقیت تجاری نیست. <a href="https://rankmath.com/kb/woocommerce-seo-feature-comparison/" target="_blank" rel="noopener">تفاوت امکانات Rank Math ↗</a></td></tr>
<tr><td>کشف و ایندکس</td><td>Search Console دامنه، sitemap شامل URLهای اصلی و قابل ایندکس، لینک HTML به مدل‌ها، URL Inspection برای نمونه‌ها. staging با رمز محافظت شود؛ noindex آن هنگام انتشار رفع شود.</td><td>صفحات مهم قابل خزش، وضعیت ایندکس با علت ثبت شود؛ ارسال sitemap تضمین ایندکس نیست.</td></tr>
<tr><td>فیلترها و جست‌وجو</td><td>ترکیب‌های sorting، search، tracking و فیلتر بی‌ارزش در sitemap نباشند. برای دسته منتخبِ دارای ارزش صفحه ثابت و محتوای واقعی بسازیم؛ سیاست crawl/noindex/canonical متناسب با هر نوع URL تعریف شود.</td><td>بدون انفجار URL و صفحه یتیم. اگر URL در robots مسدود شود، گوگل noindex همان صفحه را نمی‌بیند؛ canonical به‌تنهایی راه‌حل همه ترکیب‌ها نیست. <a href="https://developers.google.com/crawling/docs/faceted-navigation" target="_blank" rel="noopener">مدیریت فیلترها ↗</a></td></tr>
<tr><td>محصول و schema</td><td>Product/Breadcrumb و داده سازمان متناسب با محتوای واقعی؛ brand، SKU و MPN/GTIN فقط اگر معتبر. Offer با قیمت، ارز و موجودی واقعی از ووکامرس؛ قیمت صفر برای استعلام استفاده نشود.</td><td>schema تکراری قالب/افزونه حذف یا هماهنگ شود؛ داده و ظاهر یکسان. برای کالای استعلامی بدون قیمت، نمایش غنی محصول وعده داده نشود. <a href="https://developers.google.com/search/docs/appearance/structured-data/product-snippet" target="_blank" rel="noopener">الزامات داده محصول ↗</a></td></tr>
<tr><td>سرعت و اسلایدر</td><td>یک هیروی اصلی سبک، اندازه تصویر مشخص، WebP/AVIF مناسب، تصویر LCP بدون lazy-loading و تصاویر پایین صفحه lazy. فونت محلی با تعداد وزن محدود؛ انیمیشن و افزودنی المنتور کنترل‌شده؛ کش فقط صفحات عمومی.</td><td>هدف میدانی در صدک ۷۵: LCP ≤۲٫۵s، INP ≤۲۰۰ms، CLS ≤۰٫۱؛ ابتدا داده آزمایشگاهی، بعد داده کاربران واقعی. این مقادیر رتبه یا نتیجه تضمینی نیستند. <a href="https://developers.google.com/search/docs/appearance/core-web-vitals" target="_blank" rel="noopener">CWV رسمی ↗</a></td></tr>
<tr><td>قیمت و موجودی</td><td>تغییر قیمت از محصول/گزینه، نه المنتور. پاک‌سازی کش و هماهنگی Offer؛ واحد متر/حلقه/بسته روشن. نبود موجودی یا مدل توقف‌تولیدشده با جایگزین و وضعیت صحیح مدیریت شود.</td><td>صفحه، کارت و داده ساختاریافته مقدار همسان؛ حذف محصول فقط با تصمیم محتوایی و انتقال به مقصد مرتبط، نه ریدایرکت همه به خانه.</td></tr>
<tr><td>اعتماد و فارسی</td><td>درباره، تماس، شرایط عرضه، بازبین فنی، منبع و عکس واقعی. متن پیش‌فرض انگلیسی و عنوان‌های نمونه حذف شوند؛ نام لاتین مدل و کد در کنار عنوان فارسی حفظ شود.</td><td>هیچ ادعای نمایندگی، گواهی یا نظر مشتری ساختگی منتشر نشود؛ درباره و تماس با اطلاعات واقعی کامل باشند.</td></tr>
<tr><td>تحلیل و حریم خصوصی</td><td>رویدادهای خرید/RFQ/تماس/دیتاشیت به منبع ورودی وصل شوند. حساب و quote endpoints از کش عمومی خارج؛ دسترسی به سند با سرور کنترل شود.</td><td>هیچ ایمیل، موبایل، نام یا جزئیات خصوصی سند در Analytics؛ داده واقعی بر پایه رضایت و تنظیمات متناسب. <a href="security.html#quotes">امنیت اسناد ←</a></td></tr>
</tbody></table></div><div class="ir-note"><strong>به‌روزرسانی مهم ۲۰۲۶:</strong> طبق اطلاع رسمی گوگل، FAQ rich result از ۷ مه ۲۰۲۶ دیگر در نتایج نمایش داده نمی‌شود. FAQ کاربردی برای رفع ابهام خرید مفید است؛ برای رتبه یا نمایش ویژه آن برنامه‌ریزی نکنیم. <a href="https://developers.google.com/search/updates" target="_blank" rel="noopener">تغییرات رسمی گوگل ↗</a></div></section>

<section class="section" id="roadmap"><div class="section-head"><div><div class="kicker">۰۵ / برنامه شش‌ماهه پیشنهادی</div><h2>اول داده و زیرساخت؛ بعد پوشش و بهبود</h2><p>تقویم از زمان دریافت داده و دسترسی‌های لازم شروع می‌شود. تعدادها ظرفیت پیشنهادی یک تیم کوچک‌اند؛ به تعداد SKU واقعی و زمان بازبین فنی وابسته‌اند و وعده رتبه نیستند.</p></div></div><div class="ir-steps">
<article class="ir-step"><span>هفته ۱–۲</span><div><h3>شناخت سبد، تقاضا و ساختار</h3><p>برند و مدل‌های قابل تأمین، حاشیه سود نسبی، توان پاسخ فروش و مدارک جمع شود. برای هر خوشه نمونه SERP، نوع صفحات رقیب و قصد خرید بررسی شود. برای سایت موجود، خروجی Search Console و فهرست URLها؛ برای سایت تازه، کلمات بر اساس کاتالوگ و مصاحبه فروش.</p><span class="ir-owner">مسئول: سئو + فروش + بازبین فنی</span><div class="ir-output">تحویل: فایل مرجع کالا + نقشه کلمه → URL + ۳ خوشه اولویت‌دار + خط مبنا یا ثبت «هنوز داده نداریم».</div></div></article>
<article class="ir-step"><span>ماه ۱</span><div><h3>زیرساخت و صفحات پول‌ساز نخست</h3><p>الگوی محصول/دسته/برند، سرعت، لینک‌ها، schema و sitemap تنظیم شوند. شروع پیشنهادی: ۸–۱۲ مدل مهم، ۳ دسته، ۱–۲ برند واقعی و درباره/تماس/خدمت تأمین. فقط صفحه با داده کامل منتشر شود.</p><span class="ir-owner">مسئول: توسعه + سئو + فروش</span><div class="ir-output">تحویل: یک خوشه کامل با محصول، دسته، برند و مسیر خرید/RFQ؛ وضعیت ایندکس صفحات اصلی ثبت شود.</div></div></article>
<article class="ir-step"><span>ماه ۲</span><div><h3>محتوای تصمیم و اتصال به کالا</h3><p>تکمیل ۸–۱۲ مدل واقعی دیگر در صورت وجود، ۲–۳ راهنمای خرید و ۱–۲ مقایسه. سوالات فروش و تفاوت مدل‌ها منبع محتوا باشند؛ پیوند راهنما → دسته → محصول → درخواست برقرار شود.</p><span class="ir-owner">مسئول: نویسنده فنی + بازبین + سئو</span><div class="ir-output">تحویل: خوشه‌های مرتبط، جدول مقایسه تأییدشده، منبع هر مشخصه و رویدادهای تبدیل فعال.</div></div></article>
<article class="ir-step"><span>ماه ۳</span><div><h3>بهبود بر اساس داده نخست</h3><p>صفحات دارای impression و کلیک کم، قصد نامتناسب، ایندکس ناقص و درخواست بی‌کیفیت بررسی شوند. تیتر/اسنیپت بر اساس نیاز خریدار اصلاح، مطالب هم‌پوشان ادغام و مسیر فروش کوتاه شود.</p><span class="ir-owner">مسئول: سئو + توسعه + فروش</span><div class="ir-output">تحویل: گزارش خوشه‌ای Search Console و لید؛ فهرست اصلاحات با دلیل و اثر مشاهده‌شده، بدون نسبت دادن قطعی علت به رتبه.</div></div></article>
<article class="ir-step"><span>ماه ۴–۶</span><div><h3>گسترش خوشه موفق و اعتبار تخصصی</h3><p>خوشه‌های دارای تقاضا و امکان تأمین گسترش یابند. پروژه واقعی با مجوز انتشار، محتوای فنی اصیل، همکاری با سازنده/توزیع‌کننده و لینک‌های مرتبط حاصل از رابطه واقعی. خرید انبوه لینک و صفحات بی‌داده وارد برنامه نشوند.</p><span class="ir-owner">مسئول: سئو + فروش + فنی + روابط تجاری</span><div class="ir-output">تحویل: برنامه فصل بعد با اولویت بر اساس سفارش/RFQ واجد شرایط؛ نگه‌داری قیمت و سند ادامه دارد.</div></div></article>
</div><details class="ir-details"><summary>اگر سایت موجود باشد یا کاتالوگ خیلی بزرگ شود چه تغییر می‌کند؟</summary><div class="ir-grid ir-grid-two"><article class="ir-card"><h3>سایت موجود / مهاجرت</h3><p>قبل از تغییر قالب، URLهای ورودی‌دار، صفحات لینک‌دار، وضعیت ایندکس و داده فروش حفظ شوند. ساختار جدید با نگاشت ریدایرکت ۳۰۱ به مقصد مرتبط، canonical و sitemap هماهنگ منتشر شود. طراحی جدید همراه تغییر بی‌دلیل همه نشانی‌ها نباشد.</p></article><article class="ir-card"><h3>هزاران SKU / اتصال ERP</h3><p>قبل از واردسازی انبوه، شناسنامه داده، شناسه یکتا، صف همگام‌سازی و کنترل قیمت/موجودی ساخته شود. صفحات با اطلاعات ناکافی منتشر نشوند. توسعه اختصاصی برای یکپارچگی و کارایی انتخاب می‌شود؛ خود کدنویسی مزیت رتبه ذاتی ایجاد نمی‌کند.</p></article></div></details></section>

<section class="section" id="content"><div class="section-head"><div><div class="kicker">۰۶ / محتوای تخصصی و به‌روز</div><h2>اطلاعات قابل اعتماد را به محتوای قابل خرید تبدیل کنیم</h2></div></div><div class="ir-grid"><article class="ir-card"><small>PRODUCT BRIEF</small><h3>چک محتوای مدل</h3><ul><li>نام و پارت‌نامبر دقیق، عکس واقعی و بسته‌بندی.</li><li>مشخصات و محدودیت کاربرد با دیتاشیت و تاریخ بازبینی.</li><li>واحد، روش فروش، زمان تأمین تأییدشده و CTA همان کالا.</li><li>پرسش‌های مشتری، مدل جایگزین با دلیل فنی و لینک مرتبط.</li></ul></article><article class="ir-card"><small>TOPIC CLUSTER</small><h3>مقاله هدفمند</h3><ul><li>عنوان از پرسش واقعی فروش یا شکاف SERP انتخاب شود.</li><li>داده اصلی، تجربه پروژه و جدول مقایسه واقعی اضافه شود.</li><li>منبع معتبر و بازبین فنی مشخص باشد.</li><li>مقاله به مدل/خانواده قابل عرضه متصل شود؛ خبر بی‌ربط تولید نشود.</li></ul></article><article class="ir-card"><small>UPDATE POLICY</small><h3>بازبینی محتوا</h3><ul><li>قیمت/موجودی از عملیات فروش؛ مشخصات با تغییر دیتاشیت.</li><li>بازبینی محتوای مهم پیشنهاداً فصلی و پس از خطای گزارش‌شده.</li><li>دیتاشیت اصلی و نسخه محصول با تاریخ بازبینی نگه‌داری شود.</li><li>صرف تغییر تاریخ بدون اصلاح واقعی، بازبینی محسوب نشود.</li></ul></article></div>
<div class="ir-flow"><article><small>n8n / SOURCES</small><b>رصد منابع منتخب</b><p>سازنده، استاندارد و خبر مرتبط با سبد واقعی؛ URL و تاریخ منبع حفظ شود.</p></article><article><small>AI / DRAFT</small><b>پیش‌نویس و ساختار</b><p>خلاصه‌سازی و پیشنهاد تیتر؛ مشخصات و قیمت از روی حدس ساخته نشوند.</p></article><article><small>HUMAN / REVIEW</small><b>بازبینی فنی</b><p>مقایسه با منبع و کالا؛ حذف ادعای بدون سند، تأیید کاربرد و واحد.</p></article><article><small>WP / PUBLISH</small><b>انتشار و سنجش</b><p>پیش‌نویس وردپرس، لینک به محصولات، انتشار پس از تأیید و بررسی عملکرد.</p></article></div><div class="ir-note"><strong>قاعده انتشار:</strong> استفاده از AI برای پژوهش و پیش‌نویس ممکن است مفید باشد؛ تولید انبوه صفحه بدون ارزش افزوده می‌تواند با سیاست سوءاستفاده محتوای انبوه گوگل ناسازگار باشد. n8n ابتدا پیش‌نویس بسازد؛ انتشار خودکار بدون کنترل فنی در این پروژه پیشنهاد نمی‌شود. <a href="https://developers.google.com/search/docs/fundamentals/using-gen-ai-content" target="_blank" rel="noopener">راهنمای گوگل درباره AI ↗</a> <a href="build-paths.html#ai-editorial">گردش n8n و AI پروژه ←</a></div><div class="ir-source-row"><a href="https://developers.google.com/search/docs/fundamentals/creating-helpful-content" target="_blank" rel="noopener">محتوای مفید و قابل اعتماد ↗</a></div></section>

<section class="section" id="measurement"><div class="section-head"><div><div class="kicker">۰۷ / معیار نتیجه</div><h2>ورودی مرتبط و درخواست قابل فروش را اندازه بگیریم</h2><p>هدف عددی رشد پس از خط مبنا و داده SKU تعیین می‌شود. در نبود داده، درصد رشد ساختگی یا قول رتبه یک گزارش نمی‌کنیم.</p></div></div><div class="ir-grid ir-grid-four"><article class="ir-card"><small>DISCOVERY</small><h3>کشف صفحات</h3><p>وضعیت ایندکس URLهای هدف، علت صفحات حذف‌شده و صفحات یتیم؛ به تفکیک خوشه.</p></article><article class="ir-card"><small>SEARCH CONSOLE</small><h3>جست‌وجوی مرتبط</h3><p>کلیک، impression، CTR و موقعیت با تفکیک برند/غیربرند، مدل/دسته و دستگاه؛ موقعیت میانگین به‌تنهایی KPI نباشد.</p></article><article class="ir-card"><small>QUALIFIED LEADS</small><h3>استعلام مفید</h3><p>درخواست دارای مدل/نیاز قابل تشخیص، مقدار و راه پاسخ؛ quote_submit و quote_qualified از هم جدا باشند.</p></article><article class="ir-card"><small>SALES</small><h3>نتیجه فروش</h3><p>خرید تکمیل‌شده یا تبدیل استعلام به پیش‌فاکتور و سفارش؛ کیفیت تأمین و سرعت پاسخ فروش هم ثبت شود.</p></article></div><div class="ir-table" style="margin-top:20px"><table><thead><tr><th>نشانه</th><th>اقدام بعدی</th></tr></thead><tbody><tr><td>صفحه ایندکس نمی‌شود</td><td>دسترسی، canonical، noindex، لینک داخلی، کیفیت/تکرار و وضعیت گزارش بررسی شود؛ با افزودن مقاله بیشتر علت فنی حل نمی‌شود.</td></tr><tr><td>impression هست، کلیک کم است</td><td>قصد جست‌وجو، عنوان و توضیح واقعی عرضه با صفحه SERP مقایسه شوند؛ علت فقط عنوان نیست.</td></tr><tr><td>کلیک هست، استعلام مفید نیست</td><td>مدل، واحد، شرایط تأمین، مسیر RFQ و پوشش واقعی کالا بازبینی شوند؛ انتخاب کلمات و سرعت پاسخ هم بررسی شود.</td></tr><tr><td>RFQ هست، سفارش کم است</td><td>قیمت‌گذاری، موجودی، زمان پاسخ، شرایط مالی و کیفیت لید با فروش بررسی شود؛ همه مشکل به سئو نسبت داده نشود.</td></tr></tbody></table></div><div class="ir-note"><strong>ریتم گزارش:</strong> خطاهای حیاتی روزانه/هفتگی، گزارش خوشه و لید ماهانه، بازتنظیم اولویت‌ها هر فصل. رتبه رقبا، سرعت و بک‌لینک‌ها فقط پس از اندازه‌گیری معتبر به گزارش عددی اضافه شوند.</div></section>

<section class="section" id="development-paths"><div class="section-head"><div><div class="kicker">۰۸ / توسعه متناسب با کسب‌وکار</div><h2>هر سطح نیاز، مسیر ساخت خودش را دارد</h2></div></div><div class="ir-grid"><article class="ir-card"><span class="ir-pill">مسیر A · کاتالوگ و لید</span><h3>وودمارت سبک + RFQ</h3><p>کالاهای کم تا متوسط و قیمت ناپایدار: WooCommerce برای داده، صفحه مدل، مسیر استعلام و حساب ساده. اولویت سئو مدل/کاربرد و لید واجد شرایط است؛ checkout فقط اگر فروش آنلاین واقعی داریم.</p><ul><li>هسته داده + خانواده/برند/مدل.</li><li>فرم درخواست و endpoint پیش‌فاکتور.</li><li>نگه‌داری محتوا و سند توسط فنی/فروش.</li></ul></article><article class="ir-card"><span class="ir-pill">مسیر B · فروشگاه ترکیبی</span><h3>WooCommerce کامل + پنل فروش</h3><p>قیمت و موجودی قابل نگه‌داری: خرید آنلاین اقلام آماده و RFQ اقلام خاص؛ ورود ایمیل/پیامک، نسخه سند، قیمت و شرایط هر روش مشخص.</p><ul><li>محصول/گزینه با واحد و ارز درست.</li><li>همگام‌سازی کش و Offer؛ پایش checkout.</li><li>سئو کالا + دسته + تصمیم خرید.</li></ul></article><article class="ir-card"><span class="ir-pill">مسیر C · عملیات بزرگ B2B</span><h3>وودمارت + افزونه اختصاصی / اتصال سیستم</h3><p>شرکت چندکاربره، ERP و SKU زیاد: مالکیت سازمانی، همگام‌سازی داده و گردش تأیید در افزونه/سرویس اختصاصی؛ اگر محدودیت اندازه‌گیری‌شده جدی باشد، توسعه کامل در گزارش مسیر ساخت ارزیابی شود.</p><ul><li>شناسنامه SKU و منبع قیمت واحد.</li><li>صف همگام‌سازی و لاگ تغییر.</li><li>سئو پایدار هنگام تغییر معماری و URL.</li></ul></article></div></section>

<section class="section" id="deliverables"><div class="section-head"><div><div class="kicker">۰۹ / خروجی قابل تحویل</div><h2>فهرست کارها را به اجرای قابل پیگیری تبدیل کنیم</h2><p>تیک‌ها وضعیت یادداشت شخصی در همین مرورگرند؛ انجام خودکار یا تأیید فنی سایت واقعی محسوب نمی‌شوند.</p></div></div><div class="ir-progress"><strong id="seo-progress-label">۰ از ۱۲ مورد علامت‌خورده</strong><progress id="seo-progress" value="0" max="12" aria-label="پیشرفت یادداشت کارها"></progress><button type="button" id="seo-reset-plan">پاک‌کردن یادداشت‌ها</button></div><div class="ir-deliverables" id="seo-deliverables"></div><div class="ir-linkboard"><a href="competitors.html#competitors"><b>بازگشت به رقبا</b><span>شواهد پشت اولویت‌ها</span></a><a href="woodmart-templates.html#gallery"><b>طرح صفحات</b><span>مدل، درباره، تماس و حساب</span></a><a href="security.html#customer"><b>حساب و اسناد امن</b><span>ورود، مالکیت و نقش فروش</span></a></div></section>
'''

report('security.html','امنیت وردپرس و حساب مشتری | پرونده کابل','برنامه امنیت وردپرس و وودمارت، ورود ایمیل یا پیامک، حساب مشتری و پیش‌فاکتور خصوصی نسخه‌دار.','WordPress / WoodMart / Private customer accounts','ورود ساده؛<br><em>حساب و اسناد محافظت‌شده.</em>','نقشه اجرای امنیت برای سایت کابل: از پنل وردپرس و نقش فروش تا ورود مشتری و پیش‌فاکتورهای مخصوص همان حساب.',['امنیت در چهار لایه','ایمیل + پیامک','گردش پیش‌فاکتور خصوصی'],'assets/woodmart-studio/copper-hero.webp',SECURITY)
report('seo-roadmap.html','نقشه راه سئو کابل | رقبا، توسعه و برنامه شش‌ماهه','پلن سئو برای کابل صنعتی، شبکه، برند داخلی و تأمین پروژه؛ مسیر استعلام، خرید آنلاین و فروش ترکیبی با برنامه اجرایی شش‌ماهه.','SEO ROADMAP / COMPETITOR-LED / 2026','از یافته رقبا؛<br><em>تا برنامه رشد جست‌وجو.</em>','یک نقشه اجرایی برای ساخت سایت تخصصی کابل با وودمارت: مسیرهای متفاوت سبد کالا، معماری مدل‌ها، محتوای فنی، سئوی فنی و سنجش لید و فروش.',['۴ سناریوی کالا × ۳ مدل فروش','برنامه پیشنهادی شش‌ماهه','کار، مسئول و خروجی مشخص'],'assets/cable-technical-editorial.webp',SEO,'<script src="seo-roadmap.js?v=studio-4"></script>')
print('Security and SEO reports generated')
