"""Create display derivatives; keep source images and download links intact.

Run after visual_upgrade.py. Re-encoding happens only when the source changes.
Pillow is required; optional fonttools + brotli make local WOFF2 fonts.
"""
from pathlib import Path
from PIL import Image
import hashlib
import json
import re
import sys
import shutil
from html import escape

ROOT = Path(__file__).parent
OUT = ROOT / 'assets/optimized'
PAGES = ['index.html','competitors.html','strategy.html','build-paths.html','design.html',
         'templates.html','woodmart-templates.html','security.html','seo-roadmap.html','client-brief.html','service-plans.html']
VERSION = 'media-1'

def sources():
    return sorted([*(ROOT/'assets/templates').rglob('*.png'),
                   *(ROOT/'competitor-screenshots').glob('*.jpg'),
                   *(ROOT/'assets/editorial-2026').glob('*.webp'),
                   *(ROOT/'assets/woodmart-studio').glob('*.webp'),
                   *(ROOT/'assets').glob('*.webp'), ROOT/'industrial-cable-hero.png'])

def derivatives():
    OUT.mkdir(parents=True, exist_ok=True)
    prior = json.loads((OUT/'manifest.json').read_text('utf-8')) if (OUT/'manifest.json').exists() else {}
    items = {}
    for path in sources():
        if not path.exists(): continue
        source = path.relative_to(ROOT).as_posix()
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        old = prior.get('images', {}).get(source)
        if old and old['source_hash'] == digest and all((ROOT/v['path']).exists() for v in old['variants']):
            full=old['variants'][-1]
            if Path(full['path']).suffix=='.jpg' and path.suffix=='.jpg' and full['bytes']>path.stat().st_size:
                shutil.copyfile(path,ROOT/full['path'])
                full['bytes']=path.stat().st_size
            items[source] = old; continue
        with Image.open(path) as image:
            image.load()
            image = image.convert('RGB')
            w, h = image.size
            editorial = 'editorial-2026' in source or 'studio' in source or path.parent == ROOT/'assets' or path.parent == ROOT
            widths = [min(w, n) for n in ([480,768,1120,w] if editorial else [640,960,w])]
            variants = []
            for width in sorted(set(widths)):
                height = round(h * width / w)
                # WebP has a 16383px dimension limit. Preserve very tall evidence as progressive JPEG.
                ext = 'jpg' if max(width, height) > 16383 else 'webp'
                rel = Path(source).with_suffix('')
                dest = OUT / rel.parent / (rel.name + '-' + str(width) + '.' + ext)
                dest.parent.mkdir(parents=True, exist_ok=True)
                rendered = image if width == w else image.resize((width,height),Image.Resampling.LANCZOS)
                if ext == 'webp': rendered.save(dest,'WEBP',quality=79 if editorial else 87,method=6)
                else: rendered.save(dest,'JPEG',quality=82,optimize=True,progressive=True,subsampling=0)
                if width==w and ext=='jpg' and path.suffix=='.jpg' and dest.stat().st_size>path.stat().st_size:
                    shutil.copyfile(path,dest)
                variants.append({'path':dest.relative_to(ROOT).as_posix(),'width':width,'height':height,'bytes':dest.stat().st_size})
            items[source] = {'source_hash':digest,'width':w,'height':h,'original_bytes':path.stat().st_size,'variants':variants}
    full = sum(v['variants'][-1]['bytes'] for v in items.values())
    original = sum(v['original_bytes'] for v in items.values())
    manifest = {'version':VERSION,'quality':{'editorial_webp':79,'screenshots_webp':87,'tall_progressive_jpeg':82},
                'original_bytes':original,'full_display_bytes':full,'saved_percent':round((1-full/original)*100,1),'images':items}
    (OUT/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding='utf-8')
    # Only dynamic WoodMart gallery assets need a client-side lookup table.
    dynamic = {key:{'width':v['width'],'height':v['height'],'variants':v['variants']} for key,v in items.items() if '/templates/woodmart' in key}
    js = '/* Generated by optimize_report_media.py. */\nwindow.ReportMediaMap='+json.dumps(dynamic,ensure_ascii=False,separators=(',',':'))+';\n'
    (ROOT/'report-media-map.js').write_text(js,encoding='utf-8')
    return manifest

def image_attributes(source, item, hero=False, sizes=None):
    variants=item['variants']
    if sizes is None:
        if hero: sizes='(max-width:650px) calc(100vw - 40px), (max-width:950px) 640px, 560px'
        elif item['width'] <= 650: sizes='(max-width:650px) 260px, 390px'
        else: sizes='(max-width:650px) calc(100vw - 40px), (max-width:1100px) 80vw, 1100px'
    values={'data-media-source':source,'src' if hero else 'data-src':variants[-1]['path'],
            'srcset' if hero else 'data-srcset':', '.join(v['path']+' '+str(v['width'])+'w' for v in variants),
            'sizes' if hero else 'data-sizes':sizes,'width':str(item['width']),'height':str(item['height']),
            'loading':'eager' if hero else 'lazy','decoding':'async','fetchpriority':'high' if hero else 'low'}
    return values

def upgrade_page(path, manifest=None):
    path=Path(path)
    if path.name not in PAGES or not (OUT/'manifest.json').exists(): return
    manifest = manifest or json.loads((OUT/'manifest.json').read_text('utf-8'))
    images=manifest['images']
    s=path.read_text('utf-8')
    if 'id="report-theme-init"' not in s:
        s=s.replace('<head>','<head><script id="report-theme-init">try{var cableTheme=localStorage.getItem("cable-report-theme");if(cableTheme==="light"||cableTheme==="dark")document.documentElement.dataset.theme=cableTheme;}catch(e){}</script>',1)
    # Remove generated noscript duplicates before the next idempotent pass.
    s=re.sub(r'<noscript class="pl-fallback">.*?</noscript>','',s,flags=re.S)
    def replace_img(match):
        tag=match.group(0)
        attributes=dict(re.findall(r'([\w-]+)="([^"]*)"',tag))
        source=attributes.get('data-media-source',attributes.get('src',''))
        item=images.get(source)
        if not item:return tag
        hero=attributes.get('fetchpriority')=='high' and 'editorial-2026' in source
        thumb=bool(re.search(r'(?:rm-peek|rm-evidence|template-teaser|wm-slider-teaser)', s[max(0,match.start()-280):match.start()]))
        for key in ['src','srcset','sizes','data-src','data-srcset','data-sizes','width','height','loading','decoding','fetchpriority','data-media-source']:
            attributes.pop(key,None)
        attributes.update(image_attributes(source,item,hero,'(max-width:650px) 280px, 420px' if thumb else None))
        rebuilt='<img '+' '.join(k+'="'+escape(v,quote=True)+'"' for k,v in attributes.items())+'>'
        if hero:return rebuilt
        fallback=dict(attributes)
        for key in ['src','srcset','sizes']:fallback[key]=fallback.pop('data-'+key)
        return rebuilt+'<noscript class="pl-fallback"><img '+' '.join(k+'="'+escape(v,quote=True)+'"' for k,v in fallback.items())+'></noscript>'
    s=re.sub(r'<img\b[^>]*>',replace_img,s)
    if 'report-loading.css' not in s:s=s.replace('</head>','<link rel="stylesheet" href="report-loading.css?v='+VERSION+'"></head>',1)
    # Font preload is small and shared across all report pages.
    if 'rel="preload"' not in s and (ROOT/'assets/fonts/Vazirmatn-Regular.woff2').exists():
        s=s.replace('</head>','<link rel="preload" as="font" href="assets/fonts/Vazirmatn-Regular.woff2" type="font/woff2" crossorigin></head>',1)
    s=re.sub(r'<script src="report-(?:media-map|loading)\.js[^\"]*"></script>','',s)
    scripts=('<script src="report-media-map.js?v='+VERSION+'"></script>' if path.name=='woodmart-templates.html' else '')+'<script src="report-loading.js?v='+VERSION+'"></script>'
    if '<noscript><style>' not in s:s=s.replace('</head>','<noscript><style>img[data-src]:not([src]){display:none!important}</style></noscript></head>',1)
    # Gallery scripts run afterwards; they can call the shared responsive-image helper.
    s=re.sub(r'(?=<script src=")',lambda m:scripts,s,count=1)
    if scripts not in s:s=s.replace('</body>',scripts+'</body>',1)
    s=s.replace('woodmart-gallery.js?v=studio-4','woodmart-gallery.js?v=media-1')
    path.write_text(s,encoding='utf-8')

def fonts():
    sys.path.insert(0,str(ROOT/'tmp/font-tools'))
    try:
        from fontTools.ttLib import TTFont
    except ImportError:return
    for path in (ROOT/'assets/fonts').glob('*.ttf'):
        target=path.with_suffix('.woff2')
        if not target.exists():
            f=TTFont(path);f.flavor='woff2';f.save(target)
    for path in [ROOT/'reports-site.css']:
        s=path.read_text('utf-8')
        s=re.sub(r'url\("(assets/fonts/[^\"]+)\.ttf"\) format\("truetype"\)',r'url("\1.woff2") format("woff2")',s)
        path.write_text(s,encoding='utf-8')

if __name__=='__main__':
    fonts()
    manifest=derivatives()
    for name in PAGES:upgrade_page(ROOT/name,manifest)
    print(json.dumps({'images':len(manifest['images']),'original_MiB':round(manifest['original_bytes']/1048576,2),
        'display_MiB':round(manifest['full_display_bytes']/1048576,2),'saved_percent':manifest['saved_percent']},ensure_ascii=False))
