(function(){
  const basePages=[{id:'home',name:'صفحه اصلی',role:'صفحه وردپرس + Elementor'},{id:'catalog',name:'لیست همه کالاها',role:'WoodMart → Layouts → Products archive'},{id:'product',name:'صفحه محصول',role:'WoodMart → Layouts → Single product'}];
  const customerPages=[{id:'about',name:'درباره ما',role:'صفحه وردپرس + Elementor'},{id:'contact',name:'تماس با ما',role:'Elementor + فرم متصل به سرویس'},{id:'account',name:'حساب و پیش‌فاکتور',role:'My account Layout + افزونه پیش‌فاکتور'},{id:'login',name:'ورود ایمیل / پیامک',role:'Login/Register Layout + افزونه ورود'}];
  const motion=[
    {id:'wave',name:'موج',tag:'اسلایدر تمام‌عرض · بنفش و ذغالی',desc:'هیرو سینمایی با سه اسلاید و تصویر بزرگ کابل؛ دسته‌های مینیمال، کاروسل کالا و فروشگاه روشن در ادامه صفحه.',color:'teal',motion:true,build:'Slides → Sliders برای ساخت اسلایدر؛ Slides → Add Slide برای محتوای هر اسلاید با المنتور؛ ویجت Slider در خانه. متن و دکمه‌ها جدا از عکس‌اند. محصولات منتخب با ویجت Products در حالت Carousel؛ آرشیو با سایدبار فیلتر؛ صفحه مدل با گالری و اطلاعات پویای ووکامرس.'},
    {id:'pulse',name:'پالس',tag:'ویترین چرخشی محصول · کرم و آجری',desc:'دسته‌های کاربردی در کنار محصول شاخص؛ ترکیب عکس بزرگ، شناسه مدل و قیمت خوانا، با مسیر خرید مستقیم.',color:'clay',motion:true,build:'سایدبار کاربردها با Container و Button در المنتور؛ ویترین شاخص با Products Carousel و کارت‌های آماده وودمارت. بازسازی دقیق ترکیب بزرگ عکس و قیمتِ هیرو با محصول پویا ممکن است به الگوی سفارشی یا توسعه محدود نیاز داشته باشد؛ در نسخه استاندارد از کارت آماده Carousel استفاده می‌شود. قیمت در هر دو حالت از همان محصول ووکامرس خوانده می‌شود.'},
    {id:'orbit',name:'مدار',tag:'بنرهای ترکیبی · کاروسل برندها',desc:'اسلایدر اصلی در کنار دو بنر جمع‌وجور، هویت آبی و کهربایی و ردیف چرخشی برندها؛ برای فروشگاه واردات و نمایندگی.',color:'blue',motion:true,build:'کانتینرهای المنتور برای شبکه بنرها؛ Slider وودمارت برای بنر اصلی و Promo banner برای دو کارت جانبی؛ ویجت Brands در حالت Carousel پس از ثبت برندهای واقعی؛ Products Carousel برای کالاهای منتخب. لوگوها و نام‌های فعلی نمونه‌اند. آرشیو و محصول با Layouts Builder و داده ووکامرس ساخته می‌شوند.'}
  ];
  const fresh=[
    {id:'copper',name:'کوپر',tag:'ماکرو، مس و کنتراست',desc:'هدر تیره، تصویر تمام‌عرض و فروشگاه روشن؛ برای هویتی دقیق و متمایز با تمرکز روی جزئیات کابل.',color:'clay',build:'هدر تیره در Header Builder؛ هیرو با پس‌زمینه تصویر در کانتینر المنتور؛ تیتر و دکمه‌ها متن واقعی؛ ردیف محصول با ویجت Products. آرشیو با سایدبار فیلتر و کارت پیش‌فرض قالب؛ صفحه محصول با گالری در چپ و اطلاعات خرید در راست.'},
    {id:'atelier',name:'لاین',tag:'فروشگاه روشن و آرام',desc:'چیدمان سبک، تصویر قوسی و مسیر خرید مستقیم؛ مناسب فروشگاه با کالاهای دارای قیمت و خانواده‌های روشن.',color:'teal',build:'خانه با کانتینر دو ستونه، ویجت Image با شعاع گوشه، Heading و Button؛ خانواده‌ها با بنر یا دسته‌های محصول. آرشیو با Filters area در بالا و شبکه سه‌ستونه؛ صفحه محصول با گالری راست و ویجت‌های پویا در چپ. منحنی تصویر و فاصله‌ها از تنظیمات المنتور قابل تغییرند.'},
    {id:'depot',name:'دپو',tag:'صنعتی و پروژه‌محور',desc:'عکس انبار، تأکید لیمویی و خرید ترکیبی؛ خرید آنلاین اقلام عمومی در کنار استعلام مدل‌های سفارشی.',color:'blue',build:'بنر تمام‌عرض و لایه رنگی در المنتور؛ نوار انتخاب با Product filters وودمارت روی ویژگی‌های واقعی؛ خانواده‌ها با بنر و محصولات با Products. آرشیو با فیلتر سایدبار؛ صفحه محصول با کادر خرید در کانتینر. RFQ اقلام خاص و جست‌وجوی ترکیبی کاربرد/نوع نیازمند تنظیم یا توسعه جداگانه است.'}
  ];
  const previous=[{id:'technical',name:'تکنیکال',tag:'فنی و مدل‌محور',desc:'جست‌وجوی کد، مشخصات و دیتاشیت در مرکز تجربه؛ مناسب سبد صنعتی و خریدار مهندسی.',color:'teal'},{id:'brands',name:'براندا',tag:'واردات و نمایندگی',desc:'مرور سریع خانواده‌ها و برندها؛ معرفی هم‌زمان واردات و نمایندگی داخلی.',color:'clay'},{id:'project',name:'پروژه',tag:'خرید و استعلام B2B',desc:'مسیر استعلام با مدل، مقدار و لیست اقلام؛ مناسب فروش عمده.',color:'blue'}];
  function mount(root,themes,folder,start){
    if(!root)return;
    const pages=folder==='woodmart-sliders'?basePages.concat(customerPages):basePages;
    root.innerHTML=themes.map((theme,index)=>'<article class="wm-concept" id="wm-'+theme.id+'" data-tone="'+theme.color+'"><div class="wm-concept-head"><div><small>0'+(index+start)+' / WOODMART CONCEPT</small><h3>'+theme.name+'</h3><p>'+theme.desc+'</p></div><span class="wm-concept-tag">'+theme.tag+'</span></div><div class="wm-tabs" role="group" aria-label="انتخاب صفحه '+theme.name+'">'+pages.map((page,i)=>'<button type="button" data-page="'+page.id+'" aria-pressed="'+(i===0)+'">'+page.name+'</button>').join('')+'</div>'+pages.map((page,i)=>'<div class="wm-page" data-view="'+page.id+'" '+(i?'hidden':'')+'><div class="wm-page-meta"><strong>'+page.name+'</strong><span>'+page.role+'</span></div><div class="wm-frames"><figure><div class="wm-scroll wm-scroll-desktop" tabindex="0" aria-label="اسکرول تصویر دسکتاپ '+page.name+' '+theme.name+'"><img src="assets/templates/'+folder+'/'+theme.id+'-'+page.id+'-desktop.png" alt="نمای دسکتاپ '+page.name+' طرح '+theme.name+'" loading="lazy" decoding="async"></div><figcaption>دسکتاپ · تصویر را در همین قاب اسکرول کنید</figcaption></figure><figure><div class="wm-scroll wm-scroll-mobile" tabindex="0" aria-label="اسکرول تصویر گوشی '+page.name+' '+theme.name+'"><img src="assets/templates/'+folder+'/'+theme.id+'-'+page.id+'-mobile.png" alt="نمای گوشی '+page.name+' طرح '+theme.name+'" loading="lazy" decoding="async"></div><figcaption>گوشی · تصویر را در همین قاب اسکرول کنید</figcaption></figure></div><div class="wm-downloads"><a href="assets/templates/'+folder+'/'+theme.id+'-'+page.id+'-desktop.png" download>دریافت تصویر دسکتاپ ↓</a><a href="assets/templates/'+folder+'/'+theme.id+'-'+page.id+'-mobile.png" download>دریافت تصویر گوشی ↓</a></div></div>').join('')+(theme.build?'<details class="wm-blueprint"><summary>اجزای این طرح در وودمارت و المنتور</summary><p>'+theme.build+'</p></details>':'')+'</article>').join('');
    root.querySelectorAll('.wm-concept').forEach(concept=>concept.querySelectorAll('.wm-tabs button').forEach(button=>button.addEventListener('click',()=>{concept.querySelectorAll('.wm-tabs button').forEach(item=>item.setAttribute('aria-pressed',item===button?'true':'false'));concept.querySelectorAll('.wm-page').forEach(view=>{view.hidden=view.dataset.view!==button.dataset.page;});})));
    themes.filter(theme=>theme.motion).forEach(theme=>{root.querySelectorAll('#wm-'+theme.id+' .wm-page').forEach(view=>{const link=document.createElement('a');link.className='wm-live-page-link';link.href='woodmart-slider-render.html?theme='+theme.id+'&page='+view.dataset.view;link.textContent='باز کردن نسخه تعاملی همین صفحه ↗';link.target='_blank';link.rel='noopener';view.querySelector('.wm-downloads').append(link);});});
    themes.filter(theme=>theme.motion).forEach(theme=>{
      const preview=document.createElement('details');preview.className='wm-motion';
      preview.innerHTML='<summary><span>◉ پیش‌نمایش زنده اسلایدر '+theme.name+'</span><small>فلش، لمس و پخش خودکار</small></summary><div class="wm-motion-note"><p>با فلش‌ها، نقطه‌ها یا کشیدن تصویر بین اسلایدها جابه‌جا شوید. پخش خودکار اختیاری است؛ هنگام تعامل با محتوای اسلاید مکث می‌کند. این پیش‌نمایش HTML رفتار طرح را نشان می‌دهد؛ راهنمای اجرای وردپرسی زیر هر مجموعه آمده است.</p><a href="woodmart-slider-render.html?theme='+theme.id+'" target="_blank" rel="noopener">دیدن صفحه کامل تعاملی ↗</a></div><iframe title="پیش‌نمایش متحرک طرح '+theme.name+'" data-preview-src="woodmart-slider-render.html?theme='+theme.id+'&preview=1" loading="lazy"></iframe>';
      preview.addEventListener('toggle',()=>{const frame=preview.querySelector('iframe');if(preview.open&&!frame.hasAttribute('src'))frame.src=frame.dataset.previewSrc;});
      root.querySelector('#wm-'+theme.id+' .wm-tabs').before(preview);
    });
  }
  mount(document.getElementById('woodmart-slider-gallery'),motion,'woodmart-sliders',1);
  window.addEventListener('message',event=>{if(event.data?.type!=='woodmart-preview-height')return;const frame=[...document.querySelectorAll('.wm-motion iframe')].find(item=>item.contentWindow===event.source);const height=event.data.height;if(frame&&Number.isFinite(height)&&height>=200&&height<=4000)frame.style.height=height+'px';});
  mount(document.getElementById('woodmart-commerce-gallery'),fresh,'woodmart-commerce',4);
  mount(document.getElementById('woodmart-gallery'),previous,'woodmart',7);
  function revealArchive(){if(previous.some(p=>location.hash==='#wm-'+p.id))document.getElementById('previous-designs').open=true;if(fresh.some(p=>location.hash==='#wm-'+p.id))document.getElementById('commerce-designs').open=true;}
  revealArchive();window.addEventListener('hashchange',revealArchive);
})();
