(function () {
  const q = new URLSearchParams(location.search);
  const theme = ['technical', 'brands', 'project'].includes(q.get('theme')) ? q.get('theme') : 'technical';
  const page = ['home', 'catalog', 'product'].includes(q.get('page')) ? q.get('page') : 'home';
  const t = {
    technical: { name: 'تکنیـکال', sub: 'کاتالوگ فنی واردات کابل', tag: 'ENGINEERED CABLE SUPPLY', header: 'تأمین تخصصی کابل برای تصمیم‌های دقیق', lead: 'از پارت‌نامبر و مشخصات فنی تا استعلام تأمین؛ هر مدل مسیر روشن خودش را دارد.', accent: 'کد و دیتاشیت در مرکز تجربه' },
    brands: { name: 'براندا', sub: 'واردات و نمایندگی کابل', tag: 'CABLE BRANDS & SUPPLY', header: 'برندهای کابل، یکجا و قابل مقایسه', lead: 'سبد کابل وارداتی و تولید داخل را با دسته‌بندی، مدارک و شرایط تأمین مرور کنید.', accent: 'برند، دسته و اعتماد' },
    project: { name: 'پروژه', sub: 'مرکز خرید فنی کابل', tag: 'PROJECT CABLE DESK', header: 'از لیست اقلام پروژه تا پاسخ فروش', lead: 'مدل‌های موردنیاز را پیدا کنید، مقدار را ثبت کنید و درخواست را یکجا برای تیم فروش بفرستید.', accent: 'استعلام B2B در مسیر خرید' }
  }[theme];
  const photo = 'assets/cable-technical-editorial.webp';
  const spool = 'assets/cable-market-editorial.webp';
  const items = [
    { family:'ابزار دقیق', name:'کابل ابزار دقیق شیلددار', code:'IC-SH-2P-1.5', attrs:'۲ زوج · ۱٫۵ mm² · شیلد فویل', image:photo },
    { family:'کنترل', name:'کابل کنترل انعطاف‌پذیر', code:'CTRL-FLEX-4G2.5', attrs:'۴ رشته · ۲٫۵ mm² · روکش PVC', image:spool },
    { family:'شبکه', name:'کابل شبکه Cat6 S/FTP', code:'NET-CAT6-SFTP', attrs:'شیلددار · روکش LSZH · ۳۰۵ متر', image:photo },
    { family:'قدرت', name:'کابل قدرت فشار ضعیف', code:'PWR-0.6/1KV', attrs:'هادی مسی · روکش PVC · ۱ kV', image:spool },
    { family:'کنترل', name:'کابل کنترل شیلددار', code:'CTRL-SH-12X1.5', attrs:'۱۲ رشته · ۱٫۵ mm² · شیلددار', image:photo },
    { family:'شبکه', name:'کابل شبکه Cat6 U/UTP', code:'NET-CAT6-UTP', attrs:'۲۳ AWG · بدون شیلد · PVC', image:spool }
  ];
  const card = (p, i) => '<article class="product-card"><div class="product-photo"><img src="'+p.image+'" alt=""><span class="product-badge">'+p.family+'</span></div><div class="product-body"><small>'+p.code+'</small><h3>'+p.name+'</h3><p>'+p.attrs+'</p><div class="product-bottom"><span>مشاهده محصول ←</span><b>استعلام قیمت</b></div></div></article>';
  const head = () => '<div class="utility"><div class="container"><span>پیش‌نمایش طراحی · داده‌ها و برندها نمونه‌اند</span><span>تأمین کابل وارداتی و تولید داخل <i>·</i> پاسخ‌گویی به خرید فنی</span></div></div><header><div class="container main-header"><div class="identity"><span class="mark">◇</span><div><strong>'+t.name+'</strong><small>'+t.sub+'</small></div></div><div class="header-search">⌕ <span>جست‌وجوی نام، کد یا برند کابل</span><b>جست‌وجو</b></div><div class="header-contact"><small>مشاوره و استعلام</small><strong>ثبت درخواست ←</strong></div></div><div class="nav-shell"><nav class="container"><span>دسته‌های محصولات ▾</span><span>همه کابل‌ها</span><span>برندها</span><span>صنایع و کاربردها</span><span>دانش فنی</span><span>درباره ما</span><b>لیست استعلام <i>۰</i></b></nav></div></header>';
  const bottom = '<footer><div class="container"><b>'+t.name+' · کانسپت قابل اجرای وودمارت</b><span>تصاویر، مدل‌ها و ادعای نمایندگی در این پیش‌نمایش نمونه‌اند.</span></div></footer>';
  const categories = '<div class="category-grid"><div><span>01 / صنعت</span><b>ابزار دقیق و کنترل</b><small>برای کارخانه و خطوط تولید</small></div><div><span>02 / شبکه</span><b>کابل شبکه و دیتا</b><small>برای زیرساخت ارتباطی</small></div><div><span>03 / انرژی</span><b>قدرت و تأسیسات</b><small>برای پروژه‌های برق و ساختمان</small></div><div><span>04 / انتخاب</span><b>پیدا کردن مدل</b><small>بر اساس کد و ویژگی فنی</small></div></div>';
  function home() {
    let hero;
    if (theme === 'technical') hero = '<section class="hero technical-hero"><div class="hero-copy"><span class="eyebrow">'+t.tag+'</span><h1>تأمین تخصصی کابل، <em>با جزئیات قابل اتکا.</em></h1><p>'+t.lead+'</p><div class="hero-buttons"><b>مرور کاتالوگ ←</b><span>ارسال لیست اقلام</span></div><div class="hero-points"><span>کد مدل دقیق</span><span>مشخصات قابل فیلتر</span><span>استعلام پروژه‌ای</span></div></div><div class="hero-image"><img src="'+photo+'" alt=""><span>از انتخاب فنی تا تأمین مطمئن</span></div></section>';
    else if (theme === 'brands') hero = '<section class="hero brands-hero"><div class="hero-image"><img src="'+spool+'" alt=""></div><div class="hero-copy"><span class="eyebrow">'+t.tag+'</span><h1>برای هر نیاز، <em>برند و مدل مناسب.</em></h1><p>'+t.lead+'</p><div class="hero-buttons"><b>دیدن برندها ←</b><span>همه محصولات</span></div><div class="hero-points"><span>وارداتی</span><span>تولید داخل</span><span>مدرک فنی</span></div></div></section>';
    else hero = '<section class="hero project-hero"><div class="hero-copy"><span class="eyebrow">'+t.tag+'</span><h1>خرید کابل پروژه را <em>ساده‌تر شروع کنید.</em></h1><p>'+t.lead+'</p><div class="hero-buttons"><b>شروع استعلام ←</b><span>جست‌وجوی مدل</span></div><div class="hero-points"><span>کد</span><span>متراژ</span><span>موعد تحویل</span></div></div><div class="project-ticket"><div class="ticket-head"><small>RFQ / پیش‌نویس نمونه</small><b>درخواست تأمین کابل</b></div><div class="ticket-row"><span>۱</span><b>کابل ابزار دقیق شیلددار</b><small>۵۰۰ متر</small></div><div class="ticket-row"><span>۲</span><b>کابل کنترل انعطاف‌پذیر</b><small>۸۰۰ متر</small></div><div class="ticket-row"><span>۳</span><b>کابل شبکه Cat6</b><small>۱۲ حلقه</small></div><div class="ticket-foot">افزودن قلم + <b>تکمیل درخواست ←</b></div></div></section>';
    return '<main class="container">'+hero+'<div class="promise-bar"><span>◈ <b>تطبیق مدل</b><small>از پارت‌نامبر تا مشخصات</small></span><span>◎ <b>مدارک کنار کالا</b><small>دیتاشیت و اصالت تأییدشده</small></span><span>↗ <b>استعلام دقیق</b><small>قلم، واحد و مقدار پروژه</small></span></div><div class="section-title"><div><small>PRODUCT FAMILIES</small><h2>دسترسی سریع به خانواده‌های کابل</h2></div><span>مشاهده همه دسته‌ها ←</span></div>'+categories+'<div class="section-title"><div><small>SELECTED PRODUCTS</small><h2>مدل‌های نمونه در کاتالوگ</h2></div><span>لیست همه کالاها ←</span></div><div class="products home-products">'+items.slice(0,4).map(card).join('')+'</div><section class="split-promo"><div><small>'+t.accent+'</small><h2>اطلاعات فنی، کنار مسیر واقعی تأمین</h2><p>برای هر مدل صفحه‌ای با شناسه، ویژگی‌های قابل فیلتر، مدارک و درخواست قیمت طراحی می‌شود.</p><b>ارسال درخواست خرید ←</b></div><img src="'+spool+'" alt=""></section></main>';
  }
  function catalog() {
    return '<main class="container catalog"><div class="crumb">خانه / محصولات / همه کالاها</div><div class="archive-head"><div><small>PRODUCT ARCHIVE / WOODMART</small><h1>همه کابل‌ها <em>در یک کاتالوگ دقیق</em></h1><p>جست‌وجو و فیلتر بر پایه خانواده، برند و ویژگی واقعی هر مدل.</p></div><img src="'+spool+'" alt=""></div><div class="catalog-chips"><span>همه کالاها</span><span>کابل صنعتی</span><span>کابل شبکه</span><span>کابل کنترل</span><span>کابل قدرت</span></div><div class="toolbar"><b>۶ محصول نمایشی</b><span>فیلترها ☷</span><span>مرتب‌سازی: مرتبط‌ترین ▾</span><span>نمایش: ▦ ☰</span></div><div class="archive-layout"><aside><h3>فیلتر کالاها</h3><div><b>خانواده محصول</b><p>□ کابل ابزار دقیق <small>۱۸</small></p><p>□ کابل کنترل <small>۲۴</small></p><p>□ کابل شبکه <small>۱۶</small></p></div><div><b>نوع تأمین</b><p>□ وارداتی</p><p>□ تولید داخل</p></div><div><b>مشخصات فنی</b><p>□ شیلددار</p><p>□ روکش LSZH</p><p>□ مقاوم حرارت</p></div><div><b>مدرک</b><p>□ دارای دیتاشیت</p></div></aside><div class="archive-results"><div class="search-strip">⌕ <span>کد سازنده یا نام مدل را جست‌وجو کنید</span><b>پیدا کن</b></div><div class="products">'+items.map(card).join('')+'</div><div class="archive-end">مدل موردنظر در فهرست نیست؟ <b>درخواست تأمین کالای خاص ←</b></div></div></div></main>';
  }
  function product() {
    return '<main class="container single"><div class="crumb">خانه / کابل صنعتی / ابزار دقیق / کابل ابزار دقیق شیلددار</div><div class="single-layout"><div class="gallery"><div class="main-photo"><img src="'+photo+'" alt=""><span>تصویر مفهومی نمونه</span></div><div class="thumbs"><span><img src="'+photo+'" alt=""></span><span><img src="'+spool+'" alt=""></span><span>نمای فنی</span></div></div><div class="product-info"><small>INSTRUMENTATION / SAMPLE PRODUCT</small><h1>کابل ابزار دقیق <em>شیلددار</em></h1><div class="code-line">کد نمونه <b>IC-SH-2P-1.5</b></div><p>برای انتخاب مدل، مشخصات، مدارک و شرایط تأمین را در یک صفحه بررسی کنید. اطلاعات این پیش‌نمایش نمونه‌اند.</p><div class="mini-spec"><span><b>ساختار</b>۲ زوج · ۱٫۵ mm²</span><span><b>محافظت</b>شیلد فویل</span><span><b>روکش</b>PVC</span></div><div class="supply-box"><span><b>نوع تأمین</b> بر اساس برند و مدل واقعی</span><span><b>واحد درخواست</b> متر</span><span><b>قیمت</b> پس از استعلام</span></div><div class="quote-form"><b>استعلام همین مدل</b><div><span>مقدار موردنیاز</span><strong>۵۰۰</strong><span>متر ▾</span></div><button>افزودن به لیست استعلام ←</button></div><div class="document-link">دیتاشیت و مدارک محصول پس از تأیید اطلاعات واقعی درج می‌شود ↗</div></div></div><div class="product-tabs"><span>مشخصات فنی</span><span>توضیحات</span><span>مدارک</span><span>پرسش‌های متداول</span></div><div class="spec-area"><div><h2>مشخصات کلیدی مدل</h2><p>این جدول از ویژگی‌های واقعی WooCommerce پر می‌شود.</p><div class="spec-row"><span>خانواده</span><b>کابل ابزار دقیق</b></div><div class="spec-row"><span>تعداد زوج</span><b>۲ زوج</b></div><div class="spec-row"><span>سطح مقطع</span><b>۱٫۵ mm²</b></div><div class="spec-row"><span>نوع شیلد</span><b>فویل</b></div></div><div class="spec-note"><small>مدل‌محور و قابل استعلام</small><h2>یک صفحه مرجع برای هر کد</h2><p>عنوان، شناسه، ویژگی‌ها و مدارک به همان محصول متصل‌اند تا کاربر از جست‌وجو تا درخواست، مسیر یکپارچه داشته باشد.</p></div></div><div class="section-title"><div><small>RELATED MODELS</small><h2>مدل‌های مرتبط</h2></div><span>مقایسه مدل‌ها ←</span></div><div class="products related-products">'+items.slice(1,4).map(card).join('')+'</div></main>';
  }
  const site = document.getElementById('site');
  site.className = 'site theme-'+theme+' page-'+page;
  site.innerHTML = head() + (page === 'home' ? home() : page === 'catalog' ? catalog() : product()) + bottom;
})();
