(function(){
  const pages=[{id:'home',name:'صفحه اصلی',role:'صفحه وردپرس + Elementor'},{id:'catalog',name:'لیست همه کالاها',role:'WoodMart → Layouts → Products archive'},{id:'product',name:'صفحه محصول',role:'WoodMart → Layouts → Single product'}];
  const fresh=[
    {id:'copper',name:'کوپر',tag:'ماکرو، مس و کنتراست',desc:'هدر تیره، تصویر تمام‌عرض و فروشگاه روشن؛ برای هویتی دقیق و متمایز با تمرکز روی جزئیات کابل.',color:'clay',build:'هدر تیره در Header Builder؛ هیرو با پس‌زمینه تصویر در کانتینر المنتور؛ تیتر و دکمه‌ها متن واقعی؛ ردیف محصول با ویجت Products. آرشیو با سایدبار فیلتر و کارت پیش‌فرض قالب؛ صفحه محصول با گالری در چپ و اطلاعات خرید در راست.'},
    {id:'atelier',name:'لاین',tag:'فروشگاه روشن و آرام',desc:'چیدمان سبک، تصویر قوسی و مسیر خرید مستقیم؛ مناسب فروشگاه با کالاهای دارای قیمت و خانواده‌های روشن.',color:'teal',build:'خانه با کانتینر دو ستونه، ویجت Image با شعاع گوشه، Heading و Button؛ خانواده‌ها با بنر یا دسته‌های محصول. آرشیو با Filters area در بالا و شبکه سه‌ستونه؛ صفحه محصول با گالری راست و ویجت‌های پویا در چپ. منحنی تصویر و فاصله‌ها از تنظیمات المنتور قابل تغییرند.'},
    {id:'depot',name:'دپو',tag:'صنعتی و پروژه‌محور',desc:'عکس انبار، تأکید لیمویی و خرید ترکیبی؛ خرید آنلاین اقلام عمومی در کنار استعلام مدل‌های سفارشی.',color:'blue',build:'بنر تمام‌عرض و لایه رنگی در المنتور؛ نوار انتخاب با Product filters وودمارت روی ویژگی‌های واقعی؛ خانواده‌ها با بنر و محصولات با Products. آرشیو با فیلتر سایدبار؛ صفحه محصول با کادر خرید در کانتینر. RFQ اقلام خاص و جست‌وجوی ترکیبی کاربرد/نوع نیازمند تنظیم یا توسعه جداگانه است.'}
  ];
  const previous=[{id:'technical',name:'تکنیکال',tag:'فنی و مدل‌محور',desc:'جست‌وجوی کد، مشخصات و دیتاشیت در مرکز تجربه؛ مناسب سبد صنعتی و خریدار مهندسی.',color:'teal'},{id:'brands',name:'براندا',tag:'واردات و نمایندگی',desc:'مرور سریع خانواده‌ها و برندها؛ معرفی هم‌زمان واردات و نمایندگی داخلی.',color:'clay'},{id:'project',name:'پروژه',tag:'خرید و استعلام B2B',desc:'مسیر استعلام با مدل، مقدار و لیست اقلام؛ مناسب فروش عمده.',color:'blue'}];
  function mount(root,themes,folder,start){
    if(!root)return;
    root.innerHTML=themes.map((theme,index)=>'<article class="wm-concept" id="wm-'+theme.id+'" data-tone="'+theme.color+'"><div class="wm-concept-head"><div><small>0'+(index+start)+' / WOODMART CONCEPT</small><h3>'+theme.name+'</h3><p>'+theme.desc+'</p></div><span class="wm-concept-tag">'+theme.tag+'</span></div><div class="wm-tabs" role="group" aria-label="انتخاب صفحه '+theme.name+'">'+pages.map((page,i)=>'<button type="button" data-page="'+page.id+'" aria-pressed="'+(i===0)+'">'+page.name+'</button>').join('')+'</div>'+pages.map((page,i)=>'<div class="wm-page" data-view="'+page.id+'" '+(i?'hidden':'')+'><div class="wm-page-meta"><strong>'+page.name+'</strong><span>'+page.role+'</span></div><div class="wm-frames"><figure><div class="wm-scroll wm-scroll-desktop" tabindex="0" aria-label="اسکرول تصویر دسکتاپ '+page.name+' '+theme.name+'"><img src="assets/templates/'+folder+'/'+theme.id+'-'+page.id+'-desktop.png" alt="نمای دسکتاپ '+page.name+' طرح '+theme.name+'" loading="lazy" decoding="async"></div><figcaption>دسکتاپ · تصویر را در همین قاب اسکرول کنید</figcaption></figure><figure><div class="wm-scroll wm-scroll-mobile" tabindex="0" aria-label="اسکرول تصویر گوشی '+page.name+' '+theme.name+'"><img src="assets/templates/'+folder+'/'+theme.id+'-'+page.id+'-mobile.png" alt="نمای گوشی '+page.name+' طرح '+theme.name+'" loading="lazy" decoding="async"></div><figcaption>گوشی · تصویر را در همین قاب اسکرول کنید</figcaption></figure></div><div class="wm-downloads"><a href="assets/templates/'+folder+'/'+theme.id+'-'+page.id+'-desktop.png" download>دریافت تصویر دسکتاپ ↓</a><a href="assets/templates/'+folder+'/'+theme.id+'-'+page.id+'-mobile.png" download>دریافت تصویر گوشی ↓</a></div></div>').join('')+(theme.build?'<details class="wm-blueprint"><summary>اجزای این طرح در وودمارت و المنتور</summary><p>'+theme.build+'</p></details>':'')+'</article>').join('');
    root.querySelectorAll('.wm-concept').forEach(concept=>concept.querySelectorAll('.wm-tabs button').forEach(button=>button.addEventListener('click',()=>{concept.querySelectorAll('.wm-tabs button').forEach(item=>item.setAttribute('aria-pressed',item===button?'true':'false'));concept.querySelectorAll('.wm-page').forEach(view=>{view.hidden=view.dataset.view!==button.dataset.page;});})));
  }
  mount(document.getElementById('woodmart-commerce-gallery'),fresh,'woodmart-commerce',1);
  mount(document.getElementById('woodmart-gallery'),previous,'woodmart',4);
  function revealArchive(){if(previous.some(p=>location.hash==='#wm-'+p.id))document.getElementById('previous-designs').open=true;}
  revealArchive();window.addEventListener('hashchange',revealArchive);
})();
