<?php
// CLI-only, public-content allowlist. Never export users, requests or credentials.
if(PHP_SAPI!=='cli')exit;
require __DIR__.'/wordpress/wp-load.php';
function barad_public_export(){
 // Build privately for review. Publishing is a separate step after explicit approval.
 $root=__DIR__.'/private-publication-staging/wordpress-project';if(!is_dir($root.'/content'))mkdir($root.'/content',0777,true);
 $data=['format'=>'barad-public-project-v1','exported_at'=>'2026-10-09','source_url'=>home_url('/'),'versions'=>['wordpress'=>get_bloginfo('version'),'woocommerce'=>WC_VERSION,'elementor'=>ELEMENTOR_VERSION],'pages'=>[],'products'=>[],'terms'=>[],'media'=>[],'options'=>[]];
 $languages=[];global $wpdb;
 if($wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$wpdb->prefix.'icl_translations'))){foreach($wpdb->get_results("SELECT element_id, element_type, trid, language_code, source_language_code FROM {$wpdb->prefix}icl_translations",ARRAY_A) as $row)$languages[$row['element_type'].':'.$row['element_id']]=['language'=>$row['language_code'],'translation_group'=>$row['trid'],'source_language'=>$row['source_language_code']];}
 $public_meta=function($id,$page=false){$result=[];$allowed=['_thumbnail_id','_wp_page_template','_elementor_data','_elementor_edit_mode','_elementor_template_type','_elementor_version','_elementor_page_settings','_wpml_post_translation_editor_native','_barad_catalog_topic','_barad_catalog_language'];foreach(get_post_meta($id) as $key=>$rows){if(in_array($key,$allowed,true)||preg_match('/^_yoast_wpseo_(title|metadesc|focuskw|canonical|opengraph-title|opengraph-description|opengraph-image|opengraph-image-id)$/',$key)||preg_match('/^_barad_(size|sources|image_caption|datasheet_id|spec_status|unit|family|model|source_url|source_date)$/',$key))$result[$key]=get_post_meta($id,$key,true);}return $result;};
 foreach(get_posts(['post_type'=>'page','post_status'=>['publish','draft'],'numberposts'=>-1,'meta_key'=>'_wp_page_template','meta_value'=>'page-barad.php']) as $p){$data['pages'][]=['id'=>$p->ID,'slug'=>$p->post_name,'title'=>$p->post_title,'status'=>$p->post_status,'content'=>$p->post_content,'excerpt'=>$p->post_excerpt,'menu_order'=>$p->menu_order,'url'=>get_permalink($p),'translation'=>$languages['post_page:'.$p->ID]??['language'=>get_post_meta($p->ID,'_barad_catalog_language',true)?:'fa'],'meta'=>$public_meta($p->ID,true)];}
 foreach(wc_get_products(['status'=>['publish','draft'],'limit'=>-1]) as $p){if($p->get_meta('_barad_demo'))continue;$attributes=[];foreach($p->get_attributes() as $a)$attributes[]=['name'=>$a->get_name(),'options'=>$a->get_options(),'visible'=>$a->get_visible(),'variation'=>$a->get_variation(),'position'=>$a->get_position(),'taxonomy'=>$a->is_taxonomy()];$id=$p->get_id();$data['products'][]=['id'=>$id,'slug'=>$p->get_slug(),'name'=>$p->get_name(),'status'=>$p->get_status(),'type'=>$p->get_type(),'description'=>$p->get_description(),'short_description'=>$p->get_short_description(),'sku'=>$p->get_sku(),'regular_price'=>$p->get_regular_price(),'sale_price'=>$p->get_sale_price(),'stock_status'=>$p->get_stock_status(),'manage_stock'=>$p->get_manage_stock(),'stock_quantity'=>$p->get_stock_quantity(),'tax_status'=>$p->get_tax_status(),'image_id'=>$p->get_image_id(),'gallery_image_ids'=>$p->get_gallery_image_ids(),'category_ids'=>$p->get_category_ids(),'brand_ids'=>wp_get_post_terms($id,'product_brand',['fields'=>'ids']),'attributes'=>$attributes,'translation'=>$languages['post_product:'.$id]??['language'=>'fa'],'meta'=>$public_meta($id),'url'=>$p->get_permalink()];}
 foreach(['product_cat','product_brand'] as $taxonomy){foreach(get_terms(['taxonomy'=>$taxonomy,'hide_empty'=>false]) as $term){if(in_array($term->slug,['uncategorized','بدون-دسته‌بندی'],true))continue;$meta=[];foreach(['thumbnail_id','_barad_image_id','_barad_visual_id','_barad_catalog_description'] as $key)if(metadata_exists('term',$term->term_id,$key))$meta[$key]=get_term_meta($term->term_id,$key,true);$seo=class_exists('WPSEO_Taxonomy_Meta')?WPSEO_Taxonomy_Meta::get_term_meta($term,$taxonomy):[];$data['terms'][]=['id'=>$term->term_id,'taxonomy'=>$taxonomy,'slug'=>$term->slug,'name'=>$term->name,'description'=>$term->description,'parent'=>$term->parent,'translation'=>$languages['tax_'.$taxonomy.':'.$term->term_id]??['language'=>'fa'],'meta'=>$meta,'seo'=>array_intersect_key((array)$seo,array_flip(['wpseo_title','wpseo_desc','wpseo_focuskw','wpseo_canonical'])),'url'=>get_term_link($term)];}}
 foreach(['barad_design','barad_logo_id','barad_phone','barad_mobile','barad_email','barad_address','barad_map_url','barad_hours','barad_local_page_id','barad_company_catalog_id','barad_company_catalog_cover_id','barad_catalog_contact_icons','barad_catalog_extended_pages','barad_catalog_extended_media','woocommerce_currency','woocommerce_price_num_decimals','woocommerce_price_decimal_sep','woocommerce_price_thousand_sep','woocommerce_currency_pos','woocommerce_tax_display_shop','permalink_structure','blogname','blogdescription','page_on_front','show_on_front'] as $key)$data['options'][$key]=get_option($key);
 $data['options']['wpseo_local']=array_intersect_key(get_option('wpseo_local',[]),array_flip(['location_name','business_type','location_address','location_address_2','location_city','location_state','location_zipcode','location_country','location_phone','location_email','location_url','location_coords_lat','location_coords_long','hide_opening_hours','use_multiple_locations']));
 $serialized=rawurldecode(wp_json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));$needed=[];foreach($data['products'] as $p){$needed[$p['image_id']]=true;foreach($p['gallery_image_ids'] as $id)$needed[$id]=true;if(!empty($p['meta']['_barad_datasheet_id']))$needed[$p['meta']['_barad_datasheet_id']]=true;}
 foreach(['barad_logo_id','barad_company_catalog_id','barad_company_catalog_cover_id'] as $key)$needed[(int)$data['options'][$key]]=true;
 foreach(['barad_catalog_extended_media','barad_catalog_contact_icons'] as $key)foreach((array)$data['options'][$key] as $id)$needed[(int)$id]=true;
 foreach(get_posts(['post_type'=>'attachment','post_status'=>'inherit','numberposts'=>-1]) as $p){$path=get_post_meta($p->ID,'_wp_attached_file',true);if(!$path||(!isset($needed[$p->ID])&&!str_contains($serialized,$path)&&!preg_match('/(?:wp-image-|"id"\s*:\s*|"_thumbnail_id"\s*:\s*"?)'.$p->ID.'(?:\D|$)/',$serialized)))continue;$file=get_attached_file($p->ID);if(!is_file($file))throw new RuntimeException('Missing public media '.$p->ID);$target=$root.'/media/'.$path;if(!is_dir(dirname($target)))mkdir(dirname($target),0777,true);copy($file,$target);$data['media'][]=['id'=>$p->ID,'file'=>$path,'url'=>wp_get_attachment_url($p->ID),'title'=>$p->post_title,'alt'=>get_post_meta($p->ID,'_wp_attachment_image_alt',true),'caption'=>$p->post_excerpt,'description'=>$p->post_content,'mime'=>$p->post_mime_type,'sha256'=>hash_file('sha256',$target)];}
 file_put_contents($root.'/content/site.json',wp_json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT));
 $routes=[];foreach($data['pages'] as $p)if($p['status']==='publish')$routes[]=$p['url'];foreach($data['products'] as $p)if($p['status']==='publish')$routes[]=$p['url'];foreach($data['terms'] as $t)if(($t['translation']['language']??'fa')==='fa'&&$t['taxonomy']==='product_cat')$routes[]=$t['url'];$routes=array_values(array_unique($routes));file_put_contents($root.'/content/routes.json',wp_json_encode($routes,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));
 $summary=['pages'=>count($data['pages']),'published_pages'=>count(array_filter($data['pages'],fn($p)=>$p['status']==='publish')),'products'=>count($data['products']),'published_products'=>count(array_filter($data['products'],fn($p)=>$p['status']==='publish')),'media'=>count($data['media']),'public_routes'=>count($routes),'excluded'=>['users','passwords','requests','orders','customer-data','license-files','wp-config','database','runtime']];file_put_contents($root.'/content/export-summary.json',wp_json_encode($summary,JSON_PRETTY_PRINT));echo wp_json_encode($summary).PHP_EOL;
}
barad_public_export();
