<?php
/** Restore the public Barad content on a FRESH WordPress site. CLI only. */
if(PHP_SAPI!=='cli')exit;
$args=$argv;array_shift($args);$apply=in_array('--apply',$args,true);$dry=in_array('--dry-run',$args,true);$wp_path='';foreach($args as $arg)if(str_starts_with($arg,'--wp='))$wp_path=substr($arg,5);
$package=dirname(__DIR__);$json=$package.'/content/site.json';
if(!$wp_path||(!$apply&&!$dry)||!is_file($wp_path.'/wp-load.php')||!is_file($json)){fwrite(STDERR,"Usage: php tools/import-site.php --wp=/absolute/wordpress --dry-run | --apply\n");exit(1);}
require rtrim($wp_path,'/\\').'/wp-load.php';
function barad_restore_public_site($package,$apply){
 $data=json_decode(file_get_contents($package.'/content/site.json'),true,512,JSON_THROW_ON_ERROR);if(($data['format']??'')!=='barad-public-project-v1')throw new RuntimeException('Unsupported export');
 if(!class_exists('WC_Product_Simple')||!defined('ELEMENTOR_VERSION'))throw new RuntimeException('Activate WooCommerce and Elementor first');
 foreach($data['media'] as $m){$path=realpath($package.'/media/'.$m['file']);if(!$path||!str_starts_with($path,realpath($package.'/media').DIRECTORY_SEPARATOR)||hash_file('sha256',$path)!==$m['sha256'])throw new RuntimeException('Invalid media '.$m['id']);}
 if(get_posts(['post_type'=>'product','post_status'=>'any','numberposts'=>1])||get_posts(['post_type'=>'page','numberposts'=>1,'post_status'=>'any','meta_key'=>'_wp_page_template','meta_value'=>'page-barad.php']))throw new RuntimeException('Use a fresh installation; existing Barad pages or products would collide');
 if(!$apply){echo wp_json_encode(['valid'=>true,'pages'=>count($data['pages']),'products'=>count($data['products']),'media'=>count($data['media']),'mode'=>'dry-run']).PHP_EOL;return;}
 require_once ABSPATH.'wp-admin/includes/image.php';$map=['media'=>[],'terms'=>[],'posts'=>[]];$urls=[];$author=get_users(['role'=>'administrator','number'=>1,'fields'=>'ID'])[0]??0;if(!$author)throw new RuntimeException('Create an administrator through WordPress setup first');wp_set_current_user($author);global $wp_rewrite;$wp_rewrite->set_permalink_structure($data['options']['permalink_structure']);
 foreach($data['media'] as $m){$bits=file_get_contents($package.'/media/'.$m['file']);$upload=wp_upload_bits(basename($m['file']),null,$bits);if($upload['error'])throw new RuntimeException($upload['error']);$id=wp_insert_attachment(['post_title'=>$m['title'],'post_excerpt'=>$m['caption'],'post_content'=>$m['description'],'post_mime_type'=>$m['mime'],'post_status'=>'inherit'],$upload['file'],0,true);if(is_wp_error($id))throw new RuntimeException($id->get_error_message());update_post_meta($id,'_wp_attachment_image_alt',$m['alt']);wp_update_attachment_metadata($id,wp_generate_attachment_metadata($id,$upload['file']));$map['media'][$m['id']]=$id;$urls[$m['url']]=wp_get_attachment_url($id);}
 // Create all terms before mapping their hierarchy, including unpublished English terms.
 foreach($data['terms'] as $t){if(!taxonomy_exists($t['taxonomy']))throw new RuntimeException('Missing taxonomy '.$t['taxonomy']);$found=term_exists($t['slug'],$t['taxonomy']);$result=$found?:wp_insert_term($t['name'],$t['taxonomy'],['slug'=>$t['slug'],'description'=>$t['description']]);if(is_wp_error($result))throw new RuntimeException($result->get_error_message());$map['terms'][$t['id']]=(int)$result['term_id'];}
 foreach($data['terms'] as $t)wp_update_term($map['terms'][$t['id']],$t['taxonomy'],['parent'=>$map['terms'][$t['parent']]??0]);
 foreach($data['pages'] as $p){if(get_page_by_path($p['slug']))throw new RuntimeException('Existing page slug '.$p['slug']);$id=wp_insert_post(['post_type'=>'page','post_title'=>$p['title'],'post_name'=>$p['slug'],'post_excerpt'=>$p['excerpt'],'post_content'=>$p['content'],'post_status'=>$p['status'],'post_author'=>$author,'menu_order'=>$p['menu_order']],true);if(is_wp_error($id))throw new RuntimeException($id->get_error_message());$map['posts'][$p['id']]=$id;}
 foreach($data['products'] as $p){if($p['type']!=='simple')throw new RuntimeException('Unsupported product type');$product=new WC_Product_Simple();$product->set_name($p['name']);$product->set_slug($p['slug']);$product->set_status($p['status']);$product->set_description($p['description']);$product->set_short_description($p['short_description']);$product->set_sku($p['sku']);$product->set_regular_price($p['regular_price']);$product->set_sale_price($p['sale_price']);$product->set_stock_status($p['stock_status']);$product->set_manage_stock($p['manage_stock']);$product->set_stock_quantity($p['stock_quantity']);$product->set_tax_status($p['tax_status']);$product->set_category_ids(array_values(array_intersect_key($map['terms'],array_flip($p['category_ids']))));$product->set_image_id($map['media'][$p['image_id']]??0);$product->set_gallery_image_ids(array_values(array_intersect_key($map['media'],array_flip($p['gallery_image_ids']))));$attrs=[];foreach($p['attributes'] as $a){if($a['taxonomy'])throw new RuntimeException('Register global attribute taxonomy first: '.$a['name']);$attr=new WC_Product_Attribute();$attr->set_name($a['name']);$attr->set_options($a['options']);$attr->set_visible($a['visible']);$attr->set_variation($a['variation']);$attr->set_position($a['position']);$attrs[]=$attr;}$product->set_attributes($attrs);$id=$product->save();$map['posts'][$p['id']]=$id;wp_set_object_terms($id,array_values(array_intersect_key($map['terms'],array_flip($p['brand_ids']))),'product_brand');}
 foreach($data['pages'] as $p)$urls[$p['url']]=get_permalink($map['posts'][$p['id']]);foreach($data['products'] as $p)$urls[$p['url']]=get_permalink($map['posts'][$p['id']]);foreach($data['terms'] as $t)$urls[$t['url']]=get_term_link($map['terms'][$t['id']],$t['taxonomy']);
 uksort($urls,fn($a,$b)=>strlen($b)<=>strlen($a));
 $rewrite=function($value)use(&$rewrite,$urls,$data,$map){if(is_array($value)){if(isset($value['id'],$value['url'])&&isset($map['media'][(int)$value['id']]))$value['id']=$map['media'][(int)$value['id']];foreach($value as $key=>$item)$value[$key]=$rewrite($item);return $value;}if(!is_string($value))return $value;$value=strtr($value,$urls);$value=preg_replace_callback('/wp-image-(\d+)/',fn($m)=>'wp-image-'.($map['media'][(int)$m[1]]??$m[1]),$value);return str_replace(rtrim($data['source_url'],'/'),rtrim(home_url('/'),'/'),$value);};
 foreach(array_merge($data['pages'],$data['products']) as $p){$id=$map['posts'][$p['id']];foreach($p['meta'] as $key=>$value){if(in_array($key,['_thumbnail_id','_barad_datasheet_id','_yoast_wpseo_opengraph-image-id'],true))$value=$map['media'][(int)$value]??0;elseif($key==='_elementor_data')$value=wp_json_encode($rewrite(json_decode($value,true)),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);else $value=$rewrite($value);update_post_meta($id,$key,is_string($value)?wp_slash($value):$value);}if(isset($p['title']))wp_update_post(['ID'=>$id,'post_status'=>$p['status'],'post_content'=>$rewrite($p['content'])]);else{wp_update_post(['ID'=>$id,'post_content'=>$rewrite($p['description']),'post_excerpt'=>$rewrite($p['short_description'])]);}}
 foreach($data['terms'] as $t){foreach($t['meta'] as $key=>$value)update_term_meta($map['terms'][$t['id']],$key,str_contains($key,'image')||$key==='thumbnail_id'?($map['media'][(int)$value]??0):$rewrite($value));if(class_exists('WPSEO_Taxonomy_Meta'))foreach($t['seo'] as $key=>$value)WPSEO_Taxonomy_Meta::set_value($map['terms'][$t['id']],$t['taxonomy'],$key,$rewrite($value));}
 foreach($data['options'] as $key=>$value){if(in_array($key,['barad_logo_id','barad_company_catalog_id','barad_company_catalog_cover_id'],true))$value=$map['media'][(int)$value]??0;elseif(in_array($key,['barad_local_page_id','page_on_front'],true))$value=$map['posts'][(int)$value]??0;elseif(in_array($key,['barad_catalog_extended_media','barad_catalog_contact_icons'],true))$value=array_map(fn($id)=>$map['media'][(int)$id]??0,$value);elseif($key==='barad_catalog_extended_pages'){foreach($value as &$topics)foreach($topics as &$id)$id=$map['posts'][(int)$id]??0;unset($topics,$id);}else $value=$rewrite($value);update_option($key,$value);}
 // Keep this clone unindexed until the site owner approves its real-domain launch.
 update_option('blog_public',0);$pairs=[];foreach(['pages'=>'post_page','products'=>'post_product','terms'=>null] as $group=>$element)foreach($data[$group] as $row){$tr=$row['translation'];if(empty($tr['translation_group']))continue;$type=$element??'tax_'.$row['taxonomy'];$id=$group==='terms'?$map['terms'][$row['id']]:$map['posts'][$row['id']];$pairs[$type.':'.$tr['translation_group']][]=['id'=>$id,'language'=>$tr['language'],'source_language'=>$tr['source_language'],'element_type'=>$type];}update_option('barad_import_translation_pairs',$pairs);
 if(defined('ICL_SITEPRESS_VERSION')){foreach($pairs as $rows){usort($rows,fn($a,$b)=>($a['language']==='fa'?-1:1));$trid=null;foreach($rows as $row){$element_id=str_starts_with($row['element_type'],'tax_')?get_term($row['id'])->term_taxonomy_id:$row['id'];do_action('wpml_set_element_language_details',['element_id'=>$element_id,'element_type'=>$row['element_type'],'trid'=>$trid,'language_code'=>$row['language'],'source_language_code'=>$row['source_language']]);if(!$trid)$trid=apply_filters('wpml_element_trid',null,$element_id,$row['element_type']);}}}
 flush_rewrite_rules(false);if(class_exists('WPSEO_Sitemaps_Cache'))WPSEO_Sitemaps_Cache::clear();\Elementor\Plugin::$instance->files_manager->clear_cache();file_put_contents($package.'/import-result.local.json',wp_json_encode(['imported'=>true,'counts'=>['pages'=>count($data['pages']),'products'=>count($data['products']),'media'=>count($data['media'])],'id_map'=>$map],JSON_PRETTY_PRINT));echo "Imported public content. English remains draft. Review licensed plugins, Elementor, permalinks and SEO before launch.\n";
}
barad_restore_public_site($package,$apply);
